// GENERATED dari rumus v17 (nutKalori + fmHitung) - JANGAN diedit manual.
export interface CalProGolden {
  weightKg: number;
  ageMonths: number | null;
  maintenanceEnergyKcalPerDay: number;
  rdaKcalPerKg: number | null;
  rdaKcalPerDay: number | null;
  proteinGPerKg: number | null;
  proteinGPerDay: number | null;
}
export interface FormulaExpected {
  totalVolumeMl: number;
  concentrationKcalPerMl: number;
  totalKcalPerDay: number;
  scoops: number;
  waterMl: number;
  perFeed: { volumeMl: number; scoops: number; waterMl: number } | null;
}
export interface FormulaGolden {
  totalVolumeMl: number;
  feedsPerDay: number | null;
  concentrationKcalPerMl: number | null;
  expected: FormulaExpected;
}

export const CALPRO_GOLDEN: CalProGolden[] = [
  {
    weightKg: 3,
    ageMonths: null,
    maintenanceEnergyKcalPerDay: 300,
    rdaKcalPerKg: null,
    rdaKcalPerDay: null,
    proteinGPerKg: null,
    proteinGPerDay: null,
  },
  {
    weightKg: 3,
    ageMonths: 2,
    maintenanceEnergyKcalPerDay: 300,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 300,
    proteinGPerKg: 1.52,
    proteinGPerDay: 4.5600000000000005,
  },
  {
    weightKg: 3,
    ageMonths: 5,
    maintenanceEnergyKcalPerDay: 300,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 300,
    proteinGPerKg: 1.52,
    proteinGPerDay: 4.5600000000000005,
  },
  {
    weightKg: 3,
    ageMonths: 6,
    maintenanceEnergyKcalPerDay: 300,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 300,
    proteinGPerKg: 1.2,
    proteinGPerDay: 3.5999999999999996,
  },
  {
    weightKg: 3,
    ageMonths: 8,
    maintenanceEnergyKcalPerDay: 300,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 300,
    proteinGPerKg: 1.2,
    proteinGPerDay: 3.5999999999999996,
  },
  {
    weightKg: 3,
    ageMonths: 11,
    maintenanceEnergyKcalPerDay: 300,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 300,
    proteinGPerKg: 1.2,
    proteinGPerDay: 3.5999999999999996,
  },
  {
    weightKg: 3,
    ageMonths: 12,
    maintenanceEnergyKcalPerDay: 300,
    rdaKcalPerKg: 80,
    rdaKcalPerDay: 240,
    proteinGPerKg: 1.05,
    proteinGPerDay: 3.1500000000000004,
  },
  {
    weightKg: 3,
    ageMonths: 24,
    maintenanceEnergyKcalPerDay: 300,
    rdaKcalPerKg: 80,
    rdaKcalPerDay: 240,
    proteinGPerKg: 1.05,
    proteinGPerDay: 3.1500000000000004,
  },
  {
    weightKg: 3,
    ageMonths: 47,
    maintenanceEnergyKcalPerDay: 300,
    rdaKcalPerKg: 80,
    rdaKcalPerDay: 240,
    proteinGPerKg: 1.05,
    proteinGPerDay: 3.1500000000000004,
  },
  {
    weightKg: 3,
    ageMonths: 48,
    maintenanceEnergyKcalPerDay: 300,
    rdaKcalPerKg: 70,
    rdaKcalPerDay: 210,
    proteinGPerKg: 0.95,
    proteinGPerDay: 2.8499999999999996,
  },
  {
    weightKg: 3,
    ageMonths: 60,
    maintenanceEnergyKcalPerDay: 300,
    rdaKcalPerKg: 70,
    rdaKcalPerDay: 210,
    proteinGPerKg: 0.95,
    proteinGPerDay: 2.8499999999999996,
  },
  {
    weightKg: 3,
    ageMonths: 71,
    maintenanceEnergyKcalPerDay: 300,
    rdaKcalPerKg: 70,
    rdaKcalPerDay: 210,
    proteinGPerKg: 0.95,
    proteinGPerDay: 2.8499999999999996,
  },
  {
    weightKg: 3,
    ageMonths: 72,
    maintenanceEnergyKcalPerDay: 300,
    rdaKcalPerKg: 62,
    rdaKcalPerDay: 186,
    proteinGPerKg: 0.95,
    proteinGPerDay: 2.8499999999999996,
  },
  {
    weightKg: 3,
    ageMonths: 90,
    maintenanceEnergyKcalPerDay: 300,
    rdaKcalPerKg: 62,
    rdaKcalPerDay: 186,
    proteinGPerKg: 0.95,
    proteinGPerDay: 2.8499999999999996,
  },
  {
    weightKg: 3,
    ageMonths: 107,
    maintenanceEnergyKcalPerDay: 300,
    rdaKcalPerKg: 62,
    rdaKcalPerDay: 186,
    proteinGPerKg: 0.95,
    proteinGPerDay: 2.8499999999999996,
  },
  {
    weightKg: 3,
    ageMonths: 108,
    maintenanceEnergyKcalPerDay: 300,
    rdaKcalPerKg: 40,
    rdaKcalPerDay: 120,
    proteinGPerKg: 0.85,
    proteinGPerDay: 2.55,
  },
  {
    weightKg: 3,
    ageMonths: 120,
    maintenanceEnergyKcalPerDay: 300,
    rdaKcalPerKg: 40,
    rdaKcalPerDay: 120,
    proteinGPerKg: 0.85,
    proteinGPerDay: 2.55,
  },
  {
    weightKg: 3,
    ageMonths: 180,
    maintenanceEnergyKcalPerDay: 300,
    rdaKcalPerKg: 40,
    rdaKcalPerDay: 120,
    proteinGPerKg: 0.85,
    proteinGPerDay: 2.55,
  },
  {
    weightKg: 5,
    ageMonths: null,
    maintenanceEnergyKcalPerDay: 500,
    rdaKcalPerKg: null,
    rdaKcalPerDay: null,
    proteinGPerKg: null,
    proteinGPerDay: null,
  },
  {
    weightKg: 5,
    ageMonths: 2,
    maintenanceEnergyKcalPerDay: 500,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 500,
    proteinGPerKg: 1.52,
    proteinGPerDay: 7.6,
  },
  {
    weightKg: 5,
    ageMonths: 5,
    maintenanceEnergyKcalPerDay: 500,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 500,
    proteinGPerKg: 1.52,
    proteinGPerDay: 7.6,
  },
  {
    weightKg: 5,
    ageMonths: 6,
    maintenanceEnergyKcalPerDay: 500,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 500,
    proteinGPerKg: 1.2,
    proteinGPerDay: 6,
  },
  {
    weightKg: 5,
    ageMonths: 8,
    maintenanceEnergyKcalPerDay: 500,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 500,
    proteinGPerKg: 1.2,
    proteinGPerDay: 6,
  },
  {
    weightKg: 5,
    ageMonths: 11,
    maintenanceEnergyKcalPerDay: 500,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 500,
    proteinGPerKg: 1.2,
    proteinGPerDay: 6,
  },
  {
    weightKg: 5,
    ageMonths: 12,
    maintenanceEnergyKcalPerDay: 500,
    rdaKcalPerKg: 80,
    rdaKcalPerDay: 400,
    proteinGPerKg: 1.05,
    proteinGPerDay: 5.25,
  },
  {
    weightKg: 5,
    ageMonths: 24,
    maintenanceEnergyKcalPerDay: 500,
    rdaKcalPerKg: 80,
    rdaKcalPerDay: 400,
    proteinGPerKg: 1.05,
    proteinGPerDay: 5.25,
  },
  {
    weightKg: 5,
    ageMonths: 47,
    maintenanceEnergyKcalPerDay: 500,
    rdaKcalPerKg: 80,
    rdaKcalPerDay: 400,
    proteinGPerKg: 1.05,
    proteinGPerDay: 5.25,
  },
  {
    weightKg: 5,
    ageMonths: 48,
    maintenanceEnergyKcalPerDay: 500,
    rdaKcalPerKg: 70,
    rdaKcalPerDay: 350,
    proteinGPerKg: 0.95,
    proteinGPerDay: 4.75,
  },
  {
    weightKg: 5,
    ageMonths: 60,
    maintenanceEnergyKcalPerDay: 500,
    rdaKcalPerKg: 70,
    rdaKcalPerDay: 350,
    proteinGPerKg: 0.95,
    proteinGPerDay: 4.75,
  },
  {
    weightKg: 5,
    ageMonths: 71,
    maintenanceEnergyKcalPerDay: 500,
    rdaKcalPerKg: 70,
    rdaKcalPerDay: 350,
    proteinGPerKg: 0.95,
    proteinGPerDay: 4.75,
  },
  {
    weightKg: 5,
    ageMonths: 72,
    maintenanceEnergyKcalPerDay: 500,
    rdaKcalPerKg: 62,
    rdaKcalPerDay: 310,
    proteinGPerKg: 0.95,
    proteinGPerDay: 4.75,
  },
  {
    weightKg: 5,
    ageMonths: 90,
    maintenanceEnergyKcalPerDay: 500,
    rdaKcalPerKg: 62,
    rdaKcalPerDay: 310,
    proteinGPerKg: 0.95,
    proteinGPerDay: 4.75,
  },
  {
    weightKg: 5,
    ageMonths: 107,
    maintenanceEnergyKcalPerDay: 500,
    rdaKcalPerKg: 62,
    rdaKcalPerDay: 310,
    proteinGPerKg: 0.95,
    proteinGPerDay: 4.75,
  },
  {
    weightKg: 5,
    ageMonths: 108,
    maintenanceEnergyKcalPerDay: 500,
    rdaKcalPerKg: 40,
    rdaKcalPerDay: 200,
    proteinGPerKg: 0.85,
    proteinGPerDay: 4.25,
  },
  {
    weightKg: 5,
    ageMonths: 120,
    maintenanceEnergyKcalPerDay: 500,
    rdaKcalPerKg: 40,
    rdaKcalPerDay: 200,
    proteinGPerKg: 0.85,
    proteinGPerDay: 4.25,
  },
  {
    weightKg: 5,
    ageMonths: 180,
    maintenanceEnergyKcalPerDay: 500,
    rdaKcalPerKg: 40,
    rdaKcalPerDay: 200,
    proteinGPerKg: 0.85,
    proteinGPerDay: 4.25,
  },
  {
    weightKg: 8,
    ageMonths: null,
    maintenanceEnergyKcalPerDay: 800,
    rdaKcalPerKg: null,
    rdaKcalPerDay: null,
    proteinGPerKg: null,
    proteinGPerDay: null,
  },
  {
    weightKg: 8,
    ageMonths: 2,
    maintenanceEnergyKcalPerDay: 800,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 800,
    proteinGPerKg: 1.52,
    proteinGPerDay: 12.16,
  },
  {
    weightKg: 8,
    ageMonths: 5,
    maintenanceEnergyKcalPerDay: 800,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 800,
    proteinGPerKg: 1.52,
    proteinGPerDay: 12.16,
  },
  {
    weightKg: 8,
    ageMonths: 6,
    maintenanceEnergyKcalPerDay: 800,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 800,
    proteinGPerKg: 1.2,
    proteinGPerDay: 9.6,
  },
  {
    weightKg: 8,
    ageMonths: 8,
    maintenanceEnergyKcalPerDay: 800,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 800,
    proteinGPerKg: 1.2,
    proteinGPerDay: 9.6,
  },
  {
    weightKg: 8,
    ageMonths: 11,
    maintenanceEnergyKcalPerDay: 800,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 800,
    proteinGPerKg: 1.2,
    proteinGPerDay: 9.6,
  },
  {
    weightKg: 8,
    ageMonths: 12,
    maintenanceEnergyKcalPerDay: 800,
    rdaKcalPerKg: 80,
    rdaKcalPerDay: 640,
    proteinGPerKg: 1.05,
    proteinGPerDay: 8.4,
  },
  {
    weightKg: 8,
    ageMonths: 24,
    maintenanceEnergyKcalPerDay: 800,
    rdaKcalPerKg: 80,
    rdaKcalPerDay: 640,
    proteinGPerKg: 1.05,
    proteinGPerDay: 8.4,
  },
  {
    weightKg: 8,
    ageMonths: 47,
    maintenanceEnergyKcalPerDay: 800,
    rdaKcalPerKg: 80,
    rdaKcalPerDay: 640,
    proteinGPerKg: 1.05,
    proteinGPerDay: 8.4,
  },
  {
    weightKg: 8,
    ageMonths: 48,
    maintenanceEnergyKcalPerDay: 800,
    rdaKcalPerKg: 70,
    rdaKcalPerDay: 560,
    proteinGPerKg: 0.95,
    proteinGPerDay: 7.6,
  },
  {
    weightKg: 8,
    ageMonths: 60,
    maintenanceEnergyKcalPerDay: 800,
    rdaKcalPerKg: 70,
    rdaKcalPerDay: 560,
    proteinGPerKg: 0.95,
    proteinGPerDay: 7.6,
  },
  {
    weightKg: 8,
    ageMonths: 71,
    maintenanceEnergyKcalPerDay: 800,
    rdaKcalPerKg: 70,
    rdaKcalPerDay: 560,
    proteinGPerKg: 0.95,
    proteinGPerDay: 7.6,
  },
  {
    weightKg: 8,
    ageMonths: 72,
    maintenanceEnergyKcalPerDay: 800,
    rdaKcalPerKg: 62,
    rdaKcalPerDay: 496,
    proteinGPerKg: 0.95,
    proteinGPerDay: 7.6,
  },
  {
    weightKg: 8,
    ageMonths: 90,
    maintenanceEnergyKcalPerDay: 800,
    rdaKcalPerKg: 62,
    rdaKcalPerDay: 496,
    proteinGPerKg: 0.95,
    proteinGPerDay: 7.6,
  },
  {
    weightKg: 8,
    ageMonths: 107,
    maintenanceEnergyKcalPerDay: 800,
    rdaKcalPerKg: 62,
    rdaKcalPerDay: 496,
    proteinGPerKg: 0.95,
    proteinGPerDay: 7.6,
  },
  {
    weightKg: 8,
    ageMonths: 108,
    maintenanceEnergyKcalPerDay: 800,
    rdaKcalPerKg: 40,
    rdaKcalPerDay: 320,
    proteinGPerKg: 0.85,
    proteinGPerDay: 6.8,
  },
  {
    weightKg: 8,
    ageMonths: 120,
    maintenanceEnergyKcalPerDay: 800,
    rdaKcalPerKg: 40,
    rdaKcalPerDay: 320,
    proteinGPerKg: 0.85,
    proteinGPerDay: 6.8,
  },
  {
    weightKg: 8,
    ageMonths: 180,
    maintenanceEnergyKcalPerDay: 800,
    rdaKcalPerKg: 40,
    rdaKcalPerDay: 320,
    proteinGPerKg: 0.85,
    proteinGPerDay: 6.8,
  },
  {
    weightKg: 10,
    ageMonths: null,
    maintenanceEnergyKcalPerDay: 1000,
    rdaKcalPerKg: null,
    rdaKcalPerDay: null,
    proteinGPerKg: null,
    proteinGPerDay: null,
  },
  {
    weightKg: 10,
    ageMonths: 2,
    maintenanceEnergyKcalPerDay: 1000,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 1000,
    proteinGPerKg: 1.52,
    proteinGPerDay: 15.2,
  },
  {
    weightKg: 10,
    ageMonths: 5,
    maintenanceEnergyKcalPerDay: 1000,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 1000,
    proteinGPerKg: 1.52,
    proteinGPerDay: 15.2,
  },
  {
    weightKg: 10,
    ageMonths: 6,
    maintenanceEnergyKcalPerDay: 1000,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 1000,
    proteinGPerKg: 1.2,
    proteinGPerDay: 12,
  },
  {
    weightKg: 10,
    ageMonths: 8,
    maintenanceEnergyKcalPerDay: 1000,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 1000,
    proteinGPerKg: 1.2,
    proteinGPerDay: 12,
  },
  {
    weightKg: 10,
    ageMonths: 11,
    maintenanceEnergyKcalPerDay: 1000,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 1000,
    proteinGPerKg: 1.2,
    proteinGPerDay: 12,
  },
  {
    weightKg: 10,
    ageMonths: 12,
    maintenanceEnergyKcalPerDay: 1000,
    rdaKcalPerKg: 80,
    rdaKcalPerDay: 800,
    proteinGPerKg: 1.05,
    proteinGPerDay: 10.5,
  },
  {
    weightKg: 10,
    ageMonths: 24,
    maintenanceEnergyKcalPerDay: 1000,
    rdaKcalPerKg: 80,
    rdaKcalPerDay: 800,
    proteinGPerKg: 1.05,
    proteinGPerDay: 10.5,
  },
  {
    weightKg: 10,
    ageMonths: 47,
    maintenanceEnergyKcalPerDay: 1000,
    rdaKcalPerKg: 80,
    rdaKcalPerDay: 800,
    proteinGPerKg: 1.05,
    proteinGPerDay: 10.5,
  },
  {
    weightKg: 10,
    ageMonths: 48,
    maintenanceEnergyKcalPerDay: 1000,
    rdaKcalPerKg: 70,
    rdaKcalPerDay: 700,
    proteinGPerKg: 0.95,
    proteinGPerDay: 9.5,
  },
  {
    weightKg: 10,
    ageMonths: 60,
    maintenanceEnergyKcalPerDay: 1000,
    rdaKcalPerKg: 70,
    rdaKcalPerDay: 700,
    proteinGPerKg: 0.95,
    proteinGPerDay: 9.5,
  },
  {
    weightKg: 10,
    ageMonths: 71,
    maintenanceEnergyKcalPerDay: 1000,
    rdaKcalPerKg: 70,
    rdaKcalPerDay: 700,
    proteinGPerKg: 0.95,
    proteinGPerDay: 9.5,
  },
  {
    weightKg: 10,
    ageMonths: 72,
    maintenanceEnergyKcalPerDay: 1000,
    rdaKcalPerKg: 62,
    rdaKcalPerDay: 620,
    proteinGPerKg: 0.95,
    proteinGPerDay: 9.5,
  },
  {
    weightKg: 10,
    ageMonths: 90,
    maintenanceEnergyKcalPerDay: 1000,
    rdaKcalPerKg: 62,
    rdaKcalPerDay: 620,
    proteinGPerKg: 0.95,
    proteinGPerDay: 9.5,
  },
  {
    weightKg: 10,
    ageMonths: 107,
    maintenanceEnergyKcalPerDay: 1000,
    rdaKcalPerKg: 62,
    rdaKcalPerDay: 620,
    proteinGPerKg: 0.95,
    proteinGPerDay: 9.5,
  },
  {
    weightKg: 10,
    ageMonths: 108,
    maintenanceEnergyKcalPerDay: 1000,
    rdaKcalPerKg: 40,
    rdaKcalPerDay: 400,
    proteinGPerKg: 0.85,
    proteinGPerDay: 8.5,
  },
  {
    weightKg: 10,
    ageMonths: 120,
    maintenanceEnergyKcalPerDay: 1000,
    rdaKcalPerKg: 40,
    rdaKcalPerDay: 400,
    proteinGPerKg: 0.85,
    proteinGPerDay: 8.5,
  },
  {
    weightKg: 10,
    ageMonths: 180,
    maintenanceEnergyKcalPerDay: 1000,
    rdaKcalPerKg: 40,
    rdaKcalPerDay: 400,
    proteinGPerKg: 0.85,
    proteinGPerDay: 8.5,
  },
  {
    weightKg: 12,
    ageMonths: null,
    maintenanceEnergyKcalPerDay: 1100,
    rdaKcalPerKg: null,
    rdaKcalPerDay: null,
    proteinGPerKg: null,
    proteinGPerDay: null,
  },
  {
    weightKg: 12,
    ageMonths: 2,
    maintenanceEnergyKcalPerDay: 1100,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 1200,
    proteinGPerKg: 1.52,
    proteinGPerDay: 18.240000000000002,
  },
  {
    weightKg: 12,
    ageMonths: 5,
    maintenanceEnergyKcalPerDay: 1100,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 1200,
    proteinGPerKg: 1.52,
    proteinGPerDay: 18.240000000000002,
  },
  {
    weightKg: 12,
    ageMonths: 6,
    maintenanceEnergyKcalPerDay: 1100,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 1200,
    proteinGPerKg: 1.2,
    proteinGPerDay: 14.399999999999999,
  },
  {
    weightKg: 12,
    ageMonths: 8,
    maintenanceEnergyKcalPerDay: 1100,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 1200,
    proteinGPerKg: 1.2,
    proteinGPerDay: 14.399999999999999,
  },
  {
    weightKg: 12,
    ageMonths: 11,
    maintenanceEnergyKcalPerDay: 1100,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 1200,
    proteinGPerKg: 1.2,
    proteinGPerDay: 14.399999999999999,
  },
  {
    weightKg: 12,
    ageMonths: 12,
    maintenanceEnergyKcalPerDay: 1100,
    rdaKcalPerKg: 80,
    rdaKcalPerDay: 960,
    proteinGPerKg: 1.05,
    proteinGPerDay: 12.600000000000001,
  },
  {
    weightKg: 12,
    ageMonths: 24,
    maintenanceEnergyKcalPerDay: 1100,
    rdaKcalPerKg: 80,
    rdaKcalPerDay: 960,
    proteinGPerKg: 1.05,
    proteinGPerDay: 12.600000000000001,
  },
  {
    weightKg: 12,
    ageMonths: 47,
    maintenanceEnergyKcalPerDay: 1100,
    rdaKcalPerKg: 80,
    rdaKcalPerDay: 960,
    proteinGPerKg: 1.05,
    proteinGPerDay: 12.600000000000001,
  },
  {
    weightKg: 12,
    ageMonths: 48,
    maintenanceEnergyKcalPerDay: 1100,
    rdaKcalPerKg: 70,
    rdaKcalPerDay: 840,
    proteinGPerKg: 0.95,
    proteinGPerDay: 11.399999999999999,
  },
  {
    weightKg: 12,
    ageMonths: 60,
    maintenanceEnergyKcalPerDay: 1100,
    rdaKcalPerKg: 70,
    rdaKcalPerDay: 840,
    proteinGPerKg: 0.95,
    proteinGPerDay: 11.399999999999999,
  },
  {
    weightKg: 12,
    ageMonths: 71,
    maintenanceEnergyKcalPerDay: 1100,
    rdaKcalPerKg: 70,
    rdaKcalPerDay: 840,
    proteinGPerKg: 0.95,
    proteinGPerDay: 11.399999999999999,
  },
  {
    weightKg: 12,
    ageMonths: 72,
    maintenanceEnergyKcalPerDay: 1100,
    rdaKcalPerKg: 62,
    rdaKcalPerDay: 744,
    proteinGPerKg: 0.95,
    proteinGPerDay: 11.399999999999999,
  },
  {
    weightKg: 12,
    ageMonths: 90,
    maintenanceEnergyKcalPerDay: 1100,
    rdaKcalPerKg: 62,
    rdaKcalPerDay: 744,
    proteinGPerKg: 0.95,
    proteinGPerDay: 11.399999999999999,
  },
  {
    weightKg: 12,
    ageMonths: 107,
    maintenanceEnergyKcalPerDay: 1100,
    rdaKcalPerKg: 62,
    rdaKcalPerDay: 744,
    proteinGPerKg: 0.95,
    proteinGPerDay: 11.399999999999999,
  },
  {
    weightKg: 12,
    ageMonths: 108,
    maintenanceEnergyKcalPerDay: 1100,
    rdaKcalPerKg: 40,
    rdaKcalPerDay: 480,
    proteinGPerKg: 0.85,
    proteinGPerDay: 10.2,
  },
  {
    weightKg: 12,
    ageMonths: 120,
    maintenanceEnergyKcalPerDay: 1100,
    rdaKcalPerKg: 40,
    rdaKcalPerDay: 480,
    proteinGPerKg: 0.85,
    proteinGPerDay: 10.2,
  },
  {
    weightKg: 12,
    ageMonths: 180,
    maintenanceEnergyKcalPerDay: 1100,
    rdaKcalPerKg: 40,
    rdaKcalPerDay: 480,
    proteinGPerKg: 0.85,
    proteinGPerDay: 10.2,
  },
  {
    weightKg: 15,
    ageMonths: null,
    maintenanceEnergyKcalPerDay: 1250,
    rdaKcalPerKg: null,
    rdaKcalPerDay: null,
    proteinGPerKg: null,
    proteinGPerDay: null,
  },
  {
    weightKg: 15,
    ageMonths: 2,
    maintenanceEnergyKcalPerDay: 1250,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 1500,
    proteinGPerKg: 1.52,
    proteinGPerDay: 22.8,
  },
  {
    weightKg: 15,
    ageMonths: 5,
    maintenanceEnergyKcalPerDay: 1250,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 1500,
    proteinGPerKg: 1.52,
    proteinGPerDay: 22.8,
  },
  {
    weightKg: 15,
    ageMonths: 6,
    maintenanceEnergyKcalPerDay: 1250,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 1500,
    proteinGPerKg: 1.2,
    proteinGPerDay: 18,
  },
  {
    weightKg: 15,
    ageMonths: 8,
    maintenanceEnergyKcalPerDay: 1250,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 1500,
    proteinGPerKg: 1.2,
    proteinGPerDay: 18,
  },
  {
    weightKg: 15,
    ageMonths: 11,
    maintenanceEnergyKcalPerDay: 1250,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 1500,
    proteinGPerKg: 1.2,
    proteinGPerDay: 18,
  },
  {
    weightKg: 15,
    ageMonths: 12,
    maintenanceEnergyKcalPerDay: 1250,
    rdaKcalPerKg: 80,
    rdaKcalPerDay: 1200,
    proteinGPerKg: 1.05,
    proteinGPerDay: 15.75,
  },
  {
    weightKg: 15,
    ageMonths: 24,
    maintenanceEnergyKcalPerDay: 1250,
    rdaKcalPerKg: 80,
    rdaKcalPerDay: 1200,
    proteinGPerKg: 1.05,
    proteinGPerDay: 15.75,
  },
  {
    weightKg: 15,
    ageMonths: 47,
    maintenanceEnergyKcalPerDay: 1250,
    rdaKcalPerKg: 80,
    rdaKcalPerDay: 1200,
    proteinGPerKg: 1.05,
    proteinGPerDay: 15.75,
  },
  {
    weightKg: 15,
    ageMonths: 48,
    maintenanceEnergyKcalPerDay: 1250,
    rdaKcalPerKg: 70,
    rdaKcalPerDay: 1050,
    proteinGPerKg: 0.95,
    proteinGPerDay: 14.25,
  },
  {
    weightKg: 15,
    ageMonths: 60,
    maintenanceEnergyKcalPerDay: 1250,
    rdaKcalPerKg: 70,
    rdaKcalPerDay: 1050,
    proteinGPerKg: 0.95,
    proteinGPerDay: 14.25,
  },
  {
    weightKg: 15,
    ageMonths: 71,
    maintenanceEnergyKcalPerDay: 1250,
    rdaKcalPerKg: 70,
    rdaKcalPerDay: 1050,
    proteinGPerKg: 0.95,
    proteinGPerDay: 14.25,
  },
  {
    weightKg: 15,
    ageMonths: 72,
    maintenanceEnergyKcalPerDay: 1250,
    rdaKcalPerKg: 62,
    rdaKcalPerDay: 930,
    proteinGPerKg: 0.95,
    proteinGPerDay: 14.25,
  },
  {
    weightKg: 15,
    ageMonths: 90,
    maintenanceEnergyKcalPerDay: 1250,
    rdaKcalPerKg: 62,
    rdaKcalPerDay: 930,
    proteinGPerKg: 0.95,
    proteinGPerDay: 14.25,
  },
  {
    weightKg: 15,
    ageMonths: 107,
    maintenanceEnergyKcalPerDay: 1250,
    rdaKcalPerKg: 62,
    rdaKcalPerDay: 930,
    proteinGPerKg: 0.95,
    proteinGPerDay: 14.25,
  },
  {
    weightKg: 15,
    ageMonths: 108,
    maintenanceEnergyKcalPerDay: 1250,
    rdaKcalPerKg: 40,
    rdaKcalPerDay: 600,
    proteinGPerKg: 0.85,
    proteinGPerDay: 12.75,
  },
  {
    weightKg: 15,
    ageMonths: 120,
    maintenanceEnergyKcalPerDay: 1250,
    rdaKcalPerKg: 40,
    rdaKcalPerDay: 600,
    proteinGPerKg: 0.85,
    proteinGPerDay: 12.75,
  },
  {
    weightKg: 15,
    ageMonths: 180,
    maintenanceEnergyKcalPerDay: 1250,
    rdaKcalPerKg: 40,
    rdaKcalPerDay: 600,
    proteinGPerKg: 0.85,
    proteinGPerDay: 12.75,
  },
  {
    weightKg: 20,
    ageMonths: null,
    maintenanceEnergyKcalPerDay: 1500,
    rdaKcalPerKg: null,
    rdaKcalPerDay: null,
    proteinGPerKg: null,
    proteinGPerDay: null,
  },
  {
    weightKg: 20,
    ageMonths: 2,
    maintenanceEnergyKcalPerDay: 1500,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 2000,
    proteinGPerKg: 1.52,
    proteinGPerDay: 30.4,
  },
  {
    weightKg: 20,
    ageMonths: 5,
    maintenanceEnergyKcalPerDay: 1500,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 2000,
    proteinGPerKg: 1.52,
    proteinGPerDay: 30.4,
  },
  {
    weightKg: 20,
    ageMonths: 6,
    maintenanceEnergyKcalPerDay: 1500,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 2000,
    proteinGPerKg: 1.2,
    proteinGPerDay: 24,
  },
  {
    weightKg: 20,
    ageMonths: 8,
    maintenanceEnergyKcalPerDay: 1500,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 2000,
    proteinGPerKg: 1.2,
    proteinGPerDay: 24,
  },
  {
    weightKg: 20,
    ageMonths: 11,
    maintenanceEnergyKcalPerDay: 1500,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 2000,
    proteinGPerKg: 1.2,
    proteinGPerDay: 24,
  },
  {
    weightKg: 20,
    ageMonths: 12,
    maintenanceEnergyKcalPerDay: 1500,
    rdaKcalPerKg: 80,
    rdaKcalPerDay: 1600,
    proteinGPerKg: 1.05,
    proteinGPerDay: 21,
  },
  {
    weightKg: 20,
    ageMonths: 24,
    maintenanceEnergyKcalPerDay: 1500,
    rdaKcalPerKg: 80,
    rdaKcalPerDay: 1600,
    proteinGPerKg: 1.05,
    proteinGPerDay: 21,
  },
  {
    weightKg: 20,
    ageMonths: 47,
    maintenanceEnergyKcalPerDay: 1500,
    rdaKcalPerKg: 80,
    rdaKcalPerDay: 1600,
    proteinGPerKg: 1.05,
    proteinGPerDay: 21,
  },
  {
    weightKg: 20,
    ageMonths: 48,
    maintenanceEnergyKcalPerDay: 1500,
    rdaKcalPerKg: 70,
    rdaKcalPerDay: 1400,
    proteinGPerKg: 0.95,
    proteinGPerDay: 19,
  },
  {
    weightKg: 20,
    ageMonths: 60,
    maintenanceEnergyKcalPerDay: 1500,
    rdaKcalPerKg: 70,
    rdaKcalPerDay: 1400,
    proteinGPerKg: 0.95,
    proteinGPerDay: 19,
  },
  {
    weightKg: 20,
    ageMonths: 71,
    maintenanceEnergyKcalPerDay: 1500,
    rdaKcalPerKg: 70,
    rdaKcalPerDay: 1400,
    proteinGPerKg: 0.95,
    proteinGPerDay: 19,
  },
  {
    weightKg: 20,
    ageMonths: 72,
    maintenanceEnergyKcalPerDay: 1500,
    rdaKcalPerKg: 62,
    rdaKcalPerDay: 1240,
    proteinGPerKg: 0.95,
    proteinGPerDay: 19,
  },
  {
    weightKg: 20,
    ageMonths: 90,
    maintenanceEnergyKcalPerDay: 1500,
    rdaKcalPerKg: 62,
    rdaKcalPerDay: 1240,
    proteinGPerKg: 0.95,
    proteinGPerDay: 19,
  },
  {
    weightKg: 20,
    ageMonths: 107,
    maintenanceEnergyKcalPerDay: 1500,
    rdaKcalPerKg: 62,
    rdaKcalPerDay: 1240,
    proteinGPerKg: 0.95,
    proteinGPerDay: 19,
  },
  {
    weightKg: 20,
    ageMonths: 108,
    maintenanceEnergyKcalPerDay: 1500,
    rdaKcalPerKg: 40,
    rdaKcalPerDay: 800,
    proteinGPerKg: 0.85,
    proteinGPerDay: 17,
  },
  {
    weightKg: 20,
    ageMonths: 120,
    maintenanceEnergyKcalPerDay: 1500,
    rdaKcalPerKg: 40,
    rdaKcalPerDay: 800,
    proteinGPerKg: 0.85,
    proteinGPerDay: 17,
  },
  {
    weightKg: 20,
    ageMonths: 180,
    maintenanceEnergyKcalPerDay: 1500,
    rdaKcalPerKg: 40,
    rdaKcalPerDay: 800,
    proteinGPerKg: 0.85,
    proteinGPerDay: 17,
  },
  {
    weightKg: 25,
    ageMonths: null,
    maintenanceEnergyKcalPerDay: 1600,
    rdaKcalPerKg: null,
    rdaKcalPerDay: null,
    proteinGPerKg: null,
    proteinGPerDay: null,
  },
  {
    weightKg: 25,
    ageMonths: 2,
    maintenanceEnergyKcalPerDay: 1600,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 2500,
    proteinGPerKg: 1.52,
    proteinGPerDay: 38,
  },
  {
    weightKg: 25,
    ageMonths: 5,
    maintenanceEnergyKcalPerDay: 1600,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 2500,
    proteinGPerKg: 1.52,
    proteinGPerDay: 38,
  },
  {
    weightKg: 25,
    ageMonths: 6,
    maintenanceEnergyKcalPerDay: 1600,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 2500,
    proteinGPerKg: 1.2,
    proteinGPerDay: 30,
  },
  {
    weightKg: 25,
    ageMonths: 8,
    maintenanceEnergyKcalPerDay: 1600,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 2500,
    proteinGPerKg: 1.2,
    proteinGPerDay: 30,
  },
  {
    weightKg: 25,
    ageMonths: 11,
    maintenanceEnergyKcalPerDay: 1600,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 2500,
    proteinGPerKg: 1.2,
    proteinGPerDay: 30,
  },
  {
    weightKg: 25,
    ageMonths: 12,
    maintenanceEnergyKcalPerDay: 1600,
    rdaKcalPerKg: 80,
    rdaKcalPerDay: 2000,
    proteinGPerKg: 1.05,
    proteinGPerDay: 26.25,
  },
  {
    weightKg: 25,
    ageMonths: 24,
    maintenanceEnergyKcalPerDay: 1600,
    rdaKcalPerKg: 80,
    rdaKcalPerDay: 2000,
    proteinGPerKg: 1.05,
    proteinGPerDay: 26.25,
  },
  {
    weightKg: 25,
    ageMonths: 47,
    maintenanceEnergyKcalPerDay: 1600,
    rdaKcalPerKg: 80,
    rdaKcalPerDay: 2000,
    proteinGPerKg: 1.05,
    proteinGPerDay: 26.25,
  },
  {
    weightKg: 25,
    ageMonths: 48,
    maintenanceEnergyKcalPerDay: 1600,
    rdaKcalPerKg: 70,
    rdaKcalPerDay: 1750,
    proteinGPerKg: 0.95,
    proteinGPerDay: 23.75,
  },
  {
    weightKg: 25,
    ageMonths: 60,
    maintenanceEnergyKcalPerDay: 1600,
    rdaKcalPerKg: 70,
    rdaKcalPerDay: 1750,
    proteinGPerKg: 0.95,
    proteinGPerDay: 23.75,
  },
  {
    weightKg: 25,
    ageMonths: 71,
    maintenanceEnergyKcalPerDay: 1600,
    rdaKcalPerKg: 70,
    rdaKcalPerDay: 1750,
    proteinGPerKg: 0.95,
    proteinGPerDay: 23.75,
  },
  {
    weightKg: 25,
    ageMonths: 72,
    maintenanceEnergyKcalPerDay: 1600,
    rdaKcalPerKg: 62,
    rdaKcalPerDay: 1550,
    proteinGPerKg: 0.95,
    proteinGPerDay: 23.75,
  },
  {
    weightKg: 25,
    ageMonths: 90,
    maintenanceEnergyKcalPerDay: 1600,
    rdaKcalPerKg: 62,
    rdaKcalPerDay: 1550,
    proteinGPerKg: 0.95,
    proteinGPerDay: 23.75,
  },
  {
    weightKg: 25,
    ageMonths: 107,
    maintenanceEnergyKcalPerDay: 1600,
    rdaKcalPerKg: 62,
    rdaKcalPerDay: 1550,
    proteinGPerKg: 0.95,
    proteinGPerDay: 23.75,
  },
  {
    weightKg: 25,
    ageMonths: 108,
    maintenanceEnergyKcalPerDay: 1600,
    rdaKcalPerKg: 40,
    rdaKcalPerDay: 1000,
    proteinGPerKg: 0.85,
    proteinGPerDay: 21.25,
  },
  {
    weightKg: 25,
    ageMonths: 120,
    maintenanceEnergyKcalPerDay: 1600,
    rdaKcalPerKg: 40,
    rdaKcalPerDay: 1000,
    proteinGPerKg: 0.85,
    proteinGPerDay: 21.25,
  },
  {
    weightKg: 25,
    ageMonths: 180,
    maintenanceEnergyKcalPerDay: 1600,
    rdaKcalPerKg: 40,
    rdaKcalPerDay: 1000,
    proteinGPerKg: 0.85,
    proteinGPerDay: 21.25,
  },
  {
    weightKg: 30,
    ageMonths: null,
    maintenanceEnergyKcalPerDay: 1700,
    rdaKcalPerKg: null,
    rdaKcalPerDay: null,
    proteinGPerKg: null,
    proteinGPerDay: null,
  },
  {
    weightKg: 30,
    ageMonths: 2,
    maintenanceEnergyKcalPerDay: 1700,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 3000,
    proteinGPerKg: 1.52,
    proteinGPerDay: 45.6,
  },
  {
    weightKg: 30,
    ageMonths: 5,
    maintenanceEnergyKcalPerDay: 1700,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 3000,
    proteinGPerKg: 1.52,
    proteinGPerDay: 45.6,
  },
  {
    weightKg: 30,
    ageMonths: 6,
    maintenanceEnergyKcalPerDay: 1700,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 3000,
    proteinGPerKg: 1.2,
    proteinGPerDay: 36,
  },
  {
    weightKg: 30,
    ageMonths: 8,
    maintenanceEnergyKcalPerDay: 1700,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 3000,
    proteinGPerKg: 1.2,
    proteinGPerDay: 36,
  },
  {
    weightKg: 30,
    ageMonths: 11,
    maintenanceEnergyKcalPerDay: 1700,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 3000,
    proteinGPerKg: 1.2,
    proteinGPerDay: 36,
  },
  {
    weightKg: 30,
    ageMonths: 12,
    maintenanceEnergyKcalPerDay: 1700,
    rdaKcalPerKg: 80,
    rdaKcalPerDay: 2400,
    proteinGPerKg: 1.05,
    proteinGPerDay: 31.5,
  },
  {
    weightKg: 30,
    ageMonths: 24,
    maintenanceEnergyKcalPerDay: 1700,
    rdaKcalPerKg: 80,
    rdaKcalPerDay: 2400,
    proteinGPerKg: 1.05,
    proteinGPerDay: 31.5,
  },
  {
    weightKg: 30,
    ageMonths: 47,
    maintenanceEnergyKcalPerDay: 1700,
    rdaKcalPerKg: 80,
    rdaKcalPerDay: 2400,
    proteinGPerKg: 1.05,
    proteinGPerDay: 31.5,
  },
  {
    weightKg: 30,
    ageMonths: 48,
    maintenanceEnergyKcalPerDay: 1700,
    rdaKcalPerKg: 70,
    rdaKcalPerDay: 2100,
    proteinGPerKg: 0.95,
    proteinGPerDay: 28.5,
  },
  {
    weightKg: 30,
    ageMonths: 60,
    maintenanceEnergyKcalPerDay: 1700,
    rdaKcalPerKg: 70,
    rdaKcalPerDay: 2100,
    proteinGPerKg: 0.95,
    proteinGPerDay: 28.5,
  },
  {
    weightKg: 30,
    ageMonths: 71,
    maintenanceEnergyKcalPerDay: 1700,
    rdaKcalPerKg: 70,
    rdaKcalPerDay: 2100,
    proteinGPerKg: 0.95,
    proteinGPerDay: 28.5,
  },
  {
    weightKg: 30,
    ageMonths: 72,
    maintenanceEnergyKcalPerDay: 1700,
    rdaKcalPerKg: 62,
    rdaKcalPerDay: 1860,
    proteinGPerKg: 0.95,
    proteinGPerDay: 28.5,
  },
  {
    weightKg: 30,
    ageMonths: 90,
    maintenanceEnergyKcalPerDay: 1700,
    rdaKcalPerKg: 62,
    rdaKcalPerDay: 1860,
    proteinGPerKg: 0.95,
    proteinGPerDay: 28.5,
  },
  {
    weightKg: 30,
    ageMonths: 107,
    maintenanceEnergyKcalPerDay: 1700,
    rdaKcalPerKg: 62,
    rdaKcalPerDay: 1860,
    proteinGPerKg: 0.95,
    proteinGPerDay: 28.5,
  },
  {
    weightKg: 30,
    ageMonths: 108,
    maintenanceEnergyKcalPerDay: 1700,
    rdaKcalPerKg: 40,
    rdaKcalPerDay: 1200,
    proteinGPerKg: 0.85,
    proteinGPerDay: 25.5,
  },
  {
    weightKg: 30,
    ageMonths: 120,
    maintenanceEnergyKcalPerDay: 1700,
    rdaKcalPerKg: 40,
    rdaKcalPerDay: 1200,
    proteinGPerKg: 0.85,
    proteinGPerDay: 25.5,
  },
  {
    weightKg: 30,
    ageMonths: 180,
    maintenanceEnergyKcalPerDay: 1700,
    rdaKcalPerKg: 40,
    rdaKcalPerDay: 1200,
    proteinGPerKg: 0.85,
    proteinGPerDay: 25.5,
  },
  {
    weightKg: 45,
    ageMonths: null,
    maintenanceEnergyKcalPerDay: 2000,
    rdaKcalPerKg: null,
    rdaKcalPerDay: null,
    proteinGPerKg: null,
    proteinGPerDay: null,
  },
  {
    weightKg: 45,
    ageMonths: 2,
    maintenanceEnergyKcalPerDay: 2000,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 4500,
    proteinGPerKg: 1.52,
    proteinGPerDay: 68.4,
  },
  {
    weightKg: 45,
    ageMonths: 5,
    maintenanceEnergyKcalPerDay: 2000,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 4500,
    proteinGPerKg: 1.52,
    proteinGPerDay: 68.4,
  },
  {
    weightKg: 45,
    ageMonths: 6,
    maintenanceEnergyKcalPerDay: 2000,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 4500,
    proteinGPerKg: 1.2,
    proteinGPerDay: 54,
  },
  {
    weightKg: 45,
    ageMonths: 8,
    maintenanceEnergyKcalPerDay: 2000,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 4500,
    proteinGPerKg: 1.2,
    proteinGPerDay: 54,
  },
  {
    weightKg: 45,
    ageMonths: 11,
    maintenanceEnergyKcalPerDay: 2000,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 4500,
    proteinGPerKg: 1.2,
    proteinGPerDay: 54,
  },
  {
    weightKg: 45,
    ageMonths: 12,
    maintenanceEnergyKcalPerDay: 2000,
    rdaKcalPerKg: 80,
    rdaKcalPerDay: 3600,
    proteinGPerKg: 1.05,
    proteinGPerDay: 47.25,
  },
  {
    weightKg: 45,
    ageMonths: 24,
    maintenanceEnergyKcalPerDay: 2000,
    rdaKcalPerKg: 80,
    rdaKcalPerDay: 3600,
    proteinGPerKg: 1.05,
    proteinGPerDay: 47.25,
  },
  {
    weightKg: 45,
    ageMonths: 47,
    maintenanceEnergyKcalPerDay: 2000,
    rdaKcalPerKg: 80,
    rdaKcalPerDay: 3600,
    proteinGPerKg: 1.05,
    proteinGPerDay: 47.25,
  },
  {
    weightKg: 45,
    ageMonths: 48,
    maintenanceEnergyKcalPerDay: 2000,
    rdaKcalPerKg: 70,
    rdaKcalPerDay: 3150,
    proteinGPerKg: 0.95,
    proteinGPerDay: 42.75,
  },
  {
    weightKg: 45,
    ageMonths: 60,
    maintenanceEnergyKcalPerDay: 2000,
    rdaKcalPerKg: 70,
    rdaKcalPerDay: 3150,
    proteinGPerKg: 0.95,
    proteinGPerDay: 42.75,
  },
  {
    weightKg: 45,
    ageMonths: 71,
    maintenanceEnergyKcalPerDay: 2000,
    rdaKcalPerKg: 70,
    rdaKcalPerDay: 3150,
    proteinGPerKg: 0.95,
    proteinGPerDay: 42.75,
  },
  {
    weightKg: 45,
    ageMonths: 72,
    maintenanceEnergyKcalPerDay: 2000,
    rdaKcalPerKg: 62,
    rdaKcalPerDay: 2790,
    proteinGPerKg: 0.95,
    proteinGPerDay: 42.75,
  },
  {
    weightKg: 45,
    ageMonths: 90,
    maintenanceEnergyKcalPerDay: 2000,
    rdaKcalPerKg: 62,
    rdaKcalPerDay: 2790,
    proteinGPerKg: 0.95,
    proteinGPerDay: 42.75,
  },
  {
    weightKg: 45,
    ageMonths: 107,
    maintenanceEnergyKcalPerDay: 2000,
    rdaKcalPerKg: 62,
    rdaKcalPerDay: 2790,
    proteinGPerKg: 0.95,
    proteinGPerDay: 42.75,
  },
  {
    weightKg: 45,
    ageMonths: 108,
    maintenanceEnergyKcalPerDay: 2000,
    rdaKcalPerKg: 40,
    rdaKcalPerDay: 1800,
    proteinGPerKg: 0.85,
    proteinGPerDay: 38.25,
  },
  {
    weightKg: 45,
    ageMonths: 120,
    maintenanceEnergyKcalPerDay: 2000,
    rdaKcalPerKg: 40,
    rdaKcalPerDay: 1800,
    proteinGPerKg: 0.85,
    proteinGPerDay: 38.25,
  },
  {
    weightKg: 45,
    ageMonths: 180,
    maintenanceEnergyKcalPerDay: 2000,
    rdaKcalPerKg: 40,
    rdaKcalPerDay: 1800,
    proteinGPerKg: 0.85,
    proteinGPerDay: 38.25,
  },
  {
    weightKg: 60,
    ageMonths: null,
    maintenanceEnergyKcalPerDay: 2300,
    rdaKcalPerKg: null,
    rdaKcalPerDay: null,
    proteinGPerKg: null,
    proteinGPerDay: null,
  },
  {
    weightKg: 60,
    ageMonths: 2,
    maintenanceEnergyKcalPerDay: 2300,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 6000,
    proteinGPerKg: 1.52,
    proteinGPerDay: 91.2,
  },
  {
    weightKg: 60,
    ageMonths: 5,
    maintenanceEnergyKcalPerDay: 2300,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 6000,
    proteinGPerKg: 1.52,
    proteinGPerDay: 91.2,
  },
  {
    weightKg: 60,
    ageMonths: 6,
    maintenanceEnergyKcalPerDay: 2300,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 6000,
    proteinGPerKg: 1.2,
    proteinGPerDay: 72,
  },
  {
    weightKg: 60,
    ageMonths: 8,
    maintenanceEnergyKcalPerDay: 2300,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 6000,
    proteinGPerKg: 1.2,
    proteinGPerDay: 72,
  },
  {
    weightKg: 60,
    ageMonths: 11,
    maintenanceEnergyKcalPerDay: 2300,
    rdaKcalPerKg: 100,
    rdaKcalPerDay: 6000,
    proteinGPerKg: 1.2,
    proteinGPerDay: 72,
  },
  {
    weightKg: 60,
    ageMonths: 12,
    maintenanceEnergyKcalPerDay: 2300,
    rdaKcalPerKg: 80,
    rdaKcalPerDay: 4800,
    proteinGPerKg: 1.05,
    proteinGPerDay: 63,
  },
  {
    weightKg: 60,
    ageMonths: 24,
    maintenanceEnergyKcalPerDay: 2300,
    rdaKcalPerKg: 80,
    rdaKcalPerDay: 4800,
    proteinGPerKg: 1.05,
    proteinGPerDay: 63,
  },
  {
    weightKg: 60,
    ageMonths: 47,
    maintenanceEnergyKcalPerDay: 2300,
    rdaKcalPerKg: 80,
    rdaKcalPerDay: 4800,
    proteinGPerKg: 1.05,
    proteinGPerDay: 63,
  },
  {
    weightKg: 60,
    ageMonths: 48,
    maintenanceEnergyKcalPerDay: 2300,
    rdaKcalPerKg: 70,
    rdaKcalPerDay: 4200,
    proteinGPerKg: 0.95,
    proteinGPerDay: 57,
  },
  {
    weightKg: 60,
    ageMonths: 60,
    maintenanceEnergyKcalPerDay: 2300,
    rdaKcalPerKg: 70,
    rdaKcalPerDay: 4200,
    proteinGPerKg: 0.95,
    proteinGPerDay: 57,
  },
  {
    weightKg: 60,
    ageMonths: 71,
    maintenanceEnergyKcalPerDay: 2300,
    rdaKcalPerKg: 70,
    rdaKcalPerDay: 4200,
    proteinGPerKg: 0.95,
    proteinGPerDay: 57,
  },
  {
    weightKg: 60,
    ageMonths: 72,
    maintenanceEnergyKcalPerDay: 2300,
    rdaKcalPerKg: 62,
    rdaKcalPerDay: 3720,
    proteinGPerKg: 0.95,
    proteinGPerDay: 57,
  },
  {
    weightKg: 60,
    ageMonths: 90,
    maintenanceEnergyKcalPerDay: 2300,
    rdaKcalPerKg: 62,
    rdaKcalPerDay: 3720,
    proteinGPerKg: 0.95,
    proteinGPerDay: 57,
  },
  {
    weightKg: 60,
    ageMonths: 107,
    maintenanceEnergyKcalPerDay: 2300,
    rdaKcalPerKg: 62,
    rdaKcalPerDay: 3720,
    proteinGPerKg: 0.95,
    proteinGPerDay: 57,
  },
  {
    weightKg: 60,
    ageMonths: 108,
    maintenanceEnergyKcalPerDay: 2300,
    rdaKcalPerKg: 40,
    rdaKcalPerDay: 2400,
    proteinGPerKg: 0.85,
    proteinGPerDay: 51,
  },
  {
    weightKg: 60,
    ageMonths: 120,
    maintenanceEnergyKcalPerDay: 2300,
    rdaKcalPerKg: 40,
    rdaKcalPerDay: 2400,
    proteinGPerKg: 0.85,
    proteinGPerDay: 51,
  },
  {
    weightKg: 60,
    ageMonths: 180,
    maintenanceEnergyKcalPerDay: 2300,
    rdaKcalPerKg: 40,
    rdaKcalPerDay: 2400,
    proteinGPerKg: 0.85,
    proteinGPerDay: 51,
  },
];

export const FORMULA_GOLDEN: FormulaGolden[] = [
  {
    totalVolumeMl: 400,
    feedsPerDay: null,
    concentrationKcalPerMl: null,
    expected: {
      totalVolumeMl: 400,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 268,
      scoops: 7,
      waterMl: 420,
      perFeed: null,
    },
  },
  {
    totalVolumeMl: 400,
    feedsPerDay: null,
    concentrationKcalPerMl: 0.67,
    expected: {
      totalVolumeMl: 400,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 268,
      scoops: 7,
      waterMl: 420,
      perFeed: null,
    },
  },
  {
    totalVolumeMl: 400,
    feedsPerDay: null,
    concentrationKcalPerMl: 1,
    expected: {
      totalVolumeMl: 400,
      concentrationKcalPerMl: 1,
      totalKcalPerDay: 400,
      scoops: 7,
      waterMl: 420,
      perFeed: null,
    },
  },
  {
    totalVolumeMl: 400,
    feedsPerDay: 0,
    concentrationKcalPerMl: null,
    expected: {
      totalVolumeMl: 400,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 268,
      scoops: 7,
      waterMl: 420,
      perFeed: null,
    },
  },
  {
    totalVolumeMl: 400,
    feedsPerDay: 0,
    concentrationKcalPerMl: 0.67,
    expected: {
      totalVolumeMl: 400,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 268,
      scoops: 7,
      waterMl: 420,
      perFeed: null,
    },
  },
  {
    totalVolumeMl: 400,
    feedsPerDay: 0,
    concentrationKcalPerMl: 1,
    expected: {
      totalVolumeMl: 400,
      concentrationKcalPerMl: 1,
      totalKcalPerDay: 400,
      scoops: 7,
      waterMl: 420,
      perFeed: null,
    },
  },
  {
    totalVolumeMl: 400,
    feedsPerDay: 6,
    concentrationKcalPerMl: null,
    expected: {
      totalVolumeMl: 400,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 268,
      scoops: 7,
      waterMl: 420,
      perFeed: {
        volumeMl: 66.66666666666667,
        scoops: 1,
        waterMl: 60,
      },
    },
  },
  {
    totalVolumeMl: 400,
    feedsPerDay: 6,
    concentrationKcalPerMl: 0.67,
    expected: {
      totalVolumeMl: 400,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 268,
      scoops: 7,
      waterMl: 420,
      perFeed: {
        volumeMl: 66.66666666666667,
        scoops: 1,
        waterMl: 60,
      },
    },
  },
  {
    totalVolumeMl: 400,
    feedsPerDay: 6,
    concentrationKcalPerMl: 1,
    expected: {
      totalVolumeMl: 400,
      concentrationKcalPerMl: 1,
      totalKcalPerDay: 400,
      scoops: 7,
      waterMl: 420,
      perFeed: {
        volumeMl: 66.66666666666667,
        scoops: 1,
        waterMl: 60,
      },
    },
  },
  {
    totalVolumeMl: 400,
    feedsPerDay: 8,
    concentrationKcalPerMl: null,
    expected: {
      totalVolumeMl: 400,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 268,
      scoops: 7,
      waterMl: 420,
      perFeed: {
        volumeMl: 50,
        scoops: 1,
        waterMl: 60,
      },
    },
  },
  {
    totalVolumeMl: 400,
    feedsPerDay: 8,
    concentrationKcalPerMl: 0.67,
    expected: {
      totalVolumeMl: 400,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 268,
      scoops: 7,
      waterMl: 420,
      perFeed: {
        volumeMl: 50,
        scoops: 1,
        waterMl: 60,
      },
    },
  },
  {
    totalVolumeMl: 400,
    feedsPerDay: 8,
    concentrationKcalPerMl: 1,
    expected: {
      totalVolumeMl: 400,
      concentrationKcalPerMl: 1,
      totalKcalPerDay: 400,
      scoops: 7,
      waterMl: 420,
      perFeed: {
        volumeMl: 50,
        scoops: 1,
        waterMl: 60,
      },
    },
  },
  {
    totalVolumeMl: 400,
    feedsPerDay: 10,
    concentrationKcalPerMl: null,
    expected: {
      totalVolumeMl: 400,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 268,
      scoops: 7,
      waterMl: 420,
      perFeed: {
        volumeMl: 40,
        scoops: 1,
        waterMl: 60,
      },
    },
  },
  {
    totalVolumeMl: 400,
    feedsPerDay: 10,
    concentrationKcalPerMl: 0.67,
    expected: {
      totalVolumeMl: 400,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 268,
      scoops: 7,
      waterMl: 420,
      perFeed: {
        volumeMl: 40,
        scoops: 1,
        waterMl: 60,
      },
    },
  },
  {
    totalVolumeMl: 400,
    feedsPerDay: 10,
    concentrationKcalPerMl: 1,
    expected: {
      totalVolumeMl: 400,
      concentrationKcalPerMl: 1,
      totalKcalPerDay: 400,
      scoops: 7,
      waterMl: 420,
      perFeed: {
        volumeMl: 40,
        scoops: 1,
        waterMl: 60,
      },
    },
  },
  {
    totalVolumeMl: 600,
    feedsPerDay: null,
    concentrationKcalPerMl: null,
    expected: {
      totalVolumeMl: 600,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 402,
      scoops: 10,
      waterMl: 600,
      perFeed: null,
    },
  },
  {
    totalVolumeMl: 600,
    feedsPerDay: null,
    concentrationKcalPerMl: 0.67,
    expected: {
      totalVolumeMl: 600,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 402,
      scoops: 10,
      waterMl: 600,
      perFeed: null,
    },
  },
  {
    totalVolumeMl: 600,
    feedsPerDay: null,
    concentrationKcalPerMl: 1,
    expected: {
      totalVolumeMl: 600,
      concentrationKcalPerMl: 1,
      totalKcalPerDay: 600,
      scoops: 10,
      waterMl: 600,
      perFeed: null,
    },
  },
  {
    totalVolumeMl: 600,
    feedsPerDay: 0,
    concentrationKcalPerMl: null,
    expected: {
      totalVolumeMl: 600,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 402,
      scoops: 10,
      waterMl: 600,
      perFeed: null,
    },
  },
  {
    totalVolumeMl: 600,
    feedsPerDay: 0,
    concentrationKcalPerMl: 0.67,
    expected: {
      totalVolumeMl: 600,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 402,
      scoops: 10,
      waterMl: 600,
      perFeed: null,
    },
  },
  {
    totalVolumeMl: 600,
    feedsPerDay: 0,
    concentrationKcalPerMl: 1,
    expected: {
      totalVolumeMl: 600,
      concentrationKcalPerMl: 1,
      totalKcalPerDay: 600,
      scoops: 10,
      waterMl: 600,
      perFeed: null,
    },
  },
  {
    totalVolumeMl: 600,
    feedsPerDay: 6,
    concentrationKcalPerMl: null,
    expected: {
      totalVolumeMl: 600,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 402,
      scoops: 10,
      waterMl: 600,
      perFeed: {
        volumeMl: 100,
        scoops: 2,
        waterMl: 120,
      },
    },
  },
  {
    totalVolumeMl: 600,
    feedsPerDay: 6,
    concentrationKcalPerMl: 0.67,
    expected: {
      totalVolumeMl: 600,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 402,
      scoops: 10,
      waterMl: 600,
      perFeed: {
        volumeMl: 100,
        scoops: 2,
        waterMl: 120,
      },
    },
  },
  {
    totalVolumeMl: 600,
    feedsPerDay: 6,
    concentrationKcalPerMl: 1,
    expected: {
      totalVolumeMl: 600,
      concentrationKcalPerMl: 1,
      totalKcalPerDay: 600,
      scoops: 10,
      waterMl: 600,
      perFeed: {
        volumeMl: 100,
        scoops: 2,
        waterMl: 120,
      },
    },
  },
  {
    totalVolumeMl: 600,
    feedsPerDay: 8,
    concentrationKcalPerMl: null,
    expected: {
      totalVolumeMl: 600,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 402,
      scoops: 10,
      waterMl: 600,
      perFeed: {
        volumeMl: 75,
        scoops: 1,
        waterMl: 60,
      },
    },
  },
  {
    totalVolumeMl: 600,
    feedsPerDay: 8,
    concentrationKcalPerMl: 0.67,
    expected: {
      totalVolumeMl: 600,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 402,
      scoops: 10,
      waterMl: 600,
      perFeed: {
        volumeMl: 75,
        scoops: 1,
        waterMl: 60,
      },
    },
  },
  {
    totalVolumeMl: 600,
    feedsPerDay: 8,
    concentrationKcalPerMl: 1,
    expected: {
      totalVolumeMl: 600,
      concentrationKcalPerMl: 1,
      totalKcalPerDay: 600,
      scoops: 10,
      waterMl: 600,
      perFeed: {
        volumeMl: 75,
        scoops: 1,
        waterMl: 60,
      },
    },
  },
  {
    totalVolumeMl: 600,
    feedsPerDay: 10,
    concentrationKcalPerMl: null,
    expected: {
      totalVolumeMl: 600,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 402,
      scoops: 10,
      waterMl: 600,
      perFeed: {
        volumeMl: 60,
        scoops: 1,
        waterMl: 60,
      },
    },
  },
  {
    totalVolumeMl: 600,
    feedsPerDay: 10,
    concentrationKcalPerMl: 0.67,
    expected: {
      totalVolumeMl: 600,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 402,
      scoops: 10,
      waterMl: 600,
      perFeed: {
        volumeMl: 60,
        scoops: 1,
        waterMl: 60,
      },
    },
  },
  {
    totalVolumeMl: 600,
    feedsPerDay: 10,
    concentrationKcalPerMl: 1,
    expected: {
      totalVolumeMl: 600,
      concentrationKcalPerMl: 1,
      totalKcalPerDay: 600,
      scoops: 10,
      waterMl: 600,
      perFeed: {
        volumeMl: 60,
        scoops: 1,
        waterMl: 60,
      },
    },
  },
  {
    totalVolumeMl: 800,
    feedsPerDay: null,
    concentrationKcalPerMl: null,
    expected: {
      totalVolumeMl: 800,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 536,
      scoops: 13,
      waterMl: 780,
      perFeed: null,
    },
  },
  {
    totalVolumeMl: 800,
    feedsPerDay: null,
    concentrationKcalPerMl: 0.67,
    expected: {
      totalVolumeMl: 800,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 536,
      scoops: 13,
      waterMl: 780,
      perFeed: null,
    },
  },
  {
    totalVolumeMl: 800,
    feedsPerDay: null,
    concentrationKcalPerMl: 1,
    expected: {
      totalVolumeMl: 800,
      concentrationKcalPerMl: 1,
      totalKcalPerDay: 800,
      scoops: 13,
      waterMl: 780,
      perFeed: null,
    },
  },
  {
    totalVolumeMl: 800,
    feedsPerDay: 0,
    concentrationKcalPerMl: null,
    expected: {
      totalVolumeMl: 800,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 536,
      scoops: 13,
      waterMl: 780,
      perFeed: null,
    },
  },
  {
    totalVolumeMl: 800,
    feedsPerDay: 0,
    concentrationKcalPerMl: 0.67,
    expected: {
      totalVolumeMl: 800,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 536,
      scoops: 13,
      waterMl: 780,
      perFeed: null,
    },
  },
  {
    totalVolumeMl: 800,
    feedsPerDay: 0,
    concentrationKcalPerMl: 1,
    expected: {
      totalVolumeMl: 800,
      concentrationKcalPerMl: 1,
      totalKcalPerDay: 800,
      scoops: 13,
      waterMl: 780,
      perFeed: null,
    },
  },
  {
    totalVolumeMl: 800,
    feedsPerDay: 6,
    concentrationKcalPerMl: null,
    expected: {
      totalVolumeMl: 800,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 536,
      scoops: 13,
      waterMl: 780,
      perFeed: {
        volumeMl: 133.33333333333334,
        scoops: 2,
        waterMl: 120,
      },
    },
  },
  {
    totalVolumeMl: 800,
    feedsPerDay: 6,
    concentrationKcalPerMl: 0.67,
    expected: {
      totalVolumeMl: 800,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 536,
      scoops: 13,
      waterMl: 780,
      perFeed: {
        volumeMl: 133.33333333333334,
        scoops: 2,
        waterMl: 120,
      },
    },
  },
  {
    totalVolumeMl: 800,
    feedsPerDay: 6,
    concentrationKcalPerMl: 1,
    expected: {
      totalVolumeMl: 800,
      concentrationKcalPerMl: 1,
      totalKcalPerDay: 800,
      scoops: 13,
      waterMl: 780,
      perFeed: {
        volumeMl: 133.33333333333334,
        scoops: 2,
        waterMl: 120,
      },
    },
  },
  {
    totalVolumeMl: 800,
    feedsPerDay: 8,
    concentrationKcalPerMl: null,
    expected: {
      totalVolumeMl: 800,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 536,
      scoops: 13,
      waterMl: 780,
      perFeed: {
        volumeMl: 100,
        scoops: 2,
        waterMl: 120,
      },
    },
  },
  {
    totalVolumeMl: 800,
    feedsPerDay: 8,
    concentrationKcalPerMl: 0.67,
    expected: {
      totalVolumeMl: 800,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 536,
      scoops: 13,
      waterMl: 780,
      perFeed: {
        volumeMl: 100,
        scoops: 2,
        waterMl: 120,
      },
    },
  },
  {
    totalVolumeMl: 800,
    feedsPerDay: 8,
    concentrationKcalPerMl: 1,
    expected: {
      totalVolumeMl: 800,
      concentrationKcalPerMl: 1,
      totalKcalPerDay: 800,
      scoops: 13,
      waterMl: 780,
      perFeed: {
        volumeMl: 100,
        scoops: 2,
        waterMl: 120,
      },
    },
  },
  {
    totalVolumeMl: 800,
    feedsPerDay: 10,
    concentrationKcalPerMl: null,
    expected: {
      totalVolumeMl: 800,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 536,
      scoops: 13,
      waterMl: 780,
      perFeed: {
        volumeMl: 80,
        scoops: 1,
        waterMl: 60,
      },
    },
  },
  {
    totalVolumeMl: 800,
    feedsPerDay: 10,
    concentrationKcalPerMl: 0.67,
    expected: {
      totalVolumeMl: 800,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 536,
      scoops: 13,
      waterMl: 780,
      perFeed: {
        volumeMl: 80,
        scoops: 1,
        waterMl: 60,
      },
    },
  },
  {
    totalVolumeMl: 800,
    feedsPerDay: 10,
    concentrationKcalPerMl: 1,
    expected: {
      totalVolumeMl: 800,
      concentrationKcalPerMl: 1,
      totalKcalPerDay: 800,
      scoops: 13,
      waterMl: 780,
      perFeed: {
        volumeMl: 80,
        scoops: 1,
        waterMl: 60,
      },
    },
  },
  {
    totalVolumeMl: 1000,
    feedsPerDay: null,
    concentrationKcalPerMl: null,
    expected: {
      totalVolumeMl: 1000,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 670,
      scoops: 17,
      waterMl: 1020,
      perFeed: null,
    },
  },
  {
    totalVolumeMl: 1000,
    feedsPerDay: null,
    concentrationKcalPerMl: 0.67,
    expected: {
      totalVolumeMl: 1000,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 670,
      scoops: 17,
      waterMl: 1020,
      perFeed: null,
    },
  },
  {
    totalVolumeMl: 1000,
    feedsPerDay: null,
    concentrationKcalPerMl: 1,
    expected: {
      totalVolumeMl: 1000,
      concentrationKcalPerMl: 1,
      totalKcalPerDay: 1000,
      scoops: 17,
      waterMl: 1020,
      perFeed: null,
    },
  },
  {
    totalVolumeMl: 1000,
    feedsPerDay: 0,
    concentrationKcalPerMl: null,
    expected: {
      totalVolumeMl: 1000,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 670,
      scoops: 17,
      waterMl: 1020,
      perFeed: null,
    },
  },
  {
    totalVolumeMl: 1000,
    feedsPerDay: 0,
    concentrationKcalPerMl: 0.67,
    expected: {
      totalVolumeMl: 1000,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 670,
      scoops: 17,
      waterMl: 1020,
      perFeed: null,
    },
  },
  {
    totalVolumeMl: 1000,
    feedsPerDay: 0,
    concentrationKcalPerMl: 1,
    expected: {
      totalVolumeMl: 1000,
      concentrationKcalPerMl: 1,
      totalKcalPerDay: 1000,
      scoops: 17,
      waterMl: 1020,
      perFeed: null,
    },
  },
  {
    totalVolumeMl: 1000,
    feedsPerDay: 6,
    concentrationKcalPerMl: null,
    expected: {
      totalVolumeMl: 1000,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 670,
      scoops: 17,
      waterMl: 1020,
      perFeed: {
        volumeMl: 166.66666666666666,
        scoops: 3,
        waterMl: 180,
      },
    },
  },
  {
    totalVolumeMl: 1000,
    feedsPerDay: 6,
    concentrationKcalPerMl: 0.67,
    expected: {
      totalVolumeMl: 1000,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 670,
      scoops: 17,
      waterMl: 1020,
      perFeed: {
        volumeMl: 166.66666666666666,
        scoops: 3,
        waterMl: 180,
      },
    },
  },
  {
    totalVolumeMl: 1000,
    feedsPerDay: 6,
    concentrationKcalPerMl: 1,
    expected: {
      totalVolumeMl: 1000,
      concentrationKcalPerMl: 1,
      totalKcalPerDay: 1000,
      scoops: 17,
      waterMl: 1020,
      perFeed: {
        volumeMl: 166.66666666666666,
        scoops: 3,
        waterMl: 180,
      },
    },
  },
  {
    totalVolumeMl: 1000,
    feedsPerDay: 8,
    concentrationKcalPerMl: null,
    expected: {
      totalVolumeMl: 1000,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 670,
      scoops: 17,
      waterMl: 1020,
      perFeed: {
        volumeMl: 125,
        scoops: 2,
        waterMl: 120,
      },
    },
  },
  {
    totalVolumeMl: 1000,
    feedsPerDay: 8,
    concentrationKcalPerMl: 0.67,
    expected: {
      totalVolumeMl: 1000,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 670,
      scoops: 17,
      waterMl: 1020,
      perFeed: {
        volumeMl: 125,
        scoops: 2,
        waterMl: 120,
      },
    },
  },
  {
    totalVolumeMl: 1000,
    feedsPerDay: 8,
    concentrationKcalPerMl: 1,
    expected: {
      totalVolumeMl: 1000,
      concentrationKcalPerMl: 1,
      totalKcalPerDay: 1000,
      scoops: 17,
      waterMl: 1020,
      perFeed: {
        volumeMl: 125,
        scoops: 2,
        waterMl: 120,
      },
    },
  },
  {
    totalVolumeMl: 1000,
    feedsPerDay: 10,
    concentrationKcalPerMl: null,
    expected: {
      totalVolumeMl: 1000,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 670,
      scoops: 17,
      waterMl: 1020,
      perFeed: {
        volumeMl: 100,
        scoops: 2,
        waterMl: 120,
      },
    },
  },
  {
    totalVolumeMl: 1000,
    feedsPerDay: 10,
    concentrationKcalPerMl: 0.67,
    expected: {
      totalVolumeMl: 1000,
      concentrationKcalPerMl: 0.67,
      totalKcalPerDay: 670,
      scoops: 17,
      waterMl: 1020,
      perFeed: {
        volumeMl: 100,
        scoops: 2,
        waterMl: 120,
      },
    },
  },
  {
    totalVolumeMl: 1000,
    feedsPerDay: 10,
    concentrationKcalPerMl: 1,
    expected: {
      totalVolumeMl: 1000,
      concentrationKcalPerMl: 1,
      totalKcalPerDay: 1000,
      scoops: 17,
      waterMl: 1020,
      perFeed: {
        volumeMl: 100,
        scoops: 2,
        waterMl: 120,
      },
    },
  },
];
