export type KpspSektor = "kasar" | "halus" | "bicara" | "sosialisasi";

export interface KpspQuestion {
  no: number;
  sektor: KpspSektor;
  sektorLabel: string;
  teks: string;
  petunjuk?: string;
}

export interface KpspAgeGroup {
  usiaBulan: number;
  namaGroup: string;
  deskripsi: string;
  pertanyaan: KpspQuestion[];
}

export type KpspJawaban = "ya" | "tidak" | null;

export interface KpspHasil {
  totalYa: number;
  totalTidak: number;
  kategori: "sesuai" | "meragukan" | "penyimpangan";
  label: string;
  saran: string;
}

export const KPSP_DATA: Record<number, KpspAgeGroup> = {
  3: {
    usiaBulan: 3,
    namaGroup: "KPSP Usia 3 Bulan",
    deskripsi: "Untuk bayi usia 3 bulan (rentang 3 - <6 bulan). Terdiri dari 10 pertanyaan perkembangan motorik kasar, motorik halus, bicara/bahasa, serta sosialisasi/kemandirian.",
    pertanyaan: [
      {
        no: 1,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Pada waktu bayi telungkup di alas yang rata, apakah ia dapat mengangkat kepalanya?",
        petunjuk: "Posisikan bayi telungkup di tempat tidur/alas datar yang aman.",
      },
      {
        no: 2,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Pada waktu bayi telungkup di alas yang rata, apakah ia dapat mengangkat kepalanya sampai setinggi 45 derajat?",
        petunjuk: "Kepala dan dada bagian atas terangkat dari alas datar.",
      },
      {
        no: 3,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Pada waktu bayi telungkup di alas yang rata, apakah ia dapat mengangkat kepalanya sampai setinggi 90 derajat dengan menumpu pada lengan bawah?",
        petunjuk: "Kepala tegak lurus dan dada terangkat, menahan beban pada kedua siku/lengan bawah.",
      },
      {
        no: 4,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Pada waktu bayi terlentang, apakah masing-masing lengan dan tungkainya bergerak secara bebas dan aktif?",
        petunjuk: "Amati gerakan tangan dan kaki kanan serta kiri saat bayi tenang/gembira.",
      },
      {
        no: 5,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Pada waktu bayi terlentang, apakah ia dapat menatap mata Anda?",
        petunjuk: "Tatap wajah bayi dari jarak kurang lebih 20–30 cm.",
      },
      {
        no: 6,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Pada waktu bayi terlentang, apakah ia melihat dan mengikuti gerakan benda/mainan yang digerakkan dari satu sisi ke sisi lain?",
        petunjuk: "Goyangkan benda berwarna cerah (merah/kuning) di depan mata bayi dan gerakkan perlahan melintas sudut 90 derajat.",
      },
      {
        no: 7,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah bayi dapat mengeluarkan suara-suara lain selain menangis (misalnya suara ngoceh halus/cooing seperti 'ooh', 'aah')?",
        petunjuk: "Dengarkan ocehan spontan saat bayi diajak bicara atau saat bermain.",
      },
      {
        no: 8,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah bayi bereaksi (terkejut, berkedip, menghentikan gerakan, atau menoleh) ketika mendengar suara keras?",
        petunjuk: "Tepuk tangan di dekat bayi tetapi tidak terlihat langsung oleh mata bayi.",
      },
      {
        no: 9,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah bayi tersenyum ketika Anda mengajak tersenyum atau berbicara kepadanya?",
        petunjuk: "Ajak bayi tersenyum dan bicara ramah di depannya.",
      },
      {
        no: 10,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah bayi membalas tersenyum atau menunjukkan kegembiraan saat disapa dan diajak bermain?",
        petunjuk: "Respons senyum sosial (social smile) ketika berinteraksi.",
      },
    ],
  },
  6: {
    usiaBulan: 6,
    namaGroup: "KPSP Usia 6 Bulan",
    deskripsi: "Untuk bayi usia 6 bulan (rentang 6 - <9 bulan). Terdiri dari 10 pertanyaan perkembangan motorik kasar, motorik halus, bicara/bahasa, serta sosialisasi/kemandirian.",
    pertanyaan: [
      {
        no: 1,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Pada waktu bayi telungkup di alas yang rata, apakah ia dapat mengangkat kepala dengan dada terangkat dan menumpu pada kedua tangan / lengan lurus?",
        petunjuk: "Dada terangkat dari alas datar, beban ditumpu dengan telapak tangan atau lengan yang lurus.",
      },
      {
        no: 2,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah bayi dapat membalikkan badannya dari posisi telungkup ke terlentang atau sebaliknya secara mandiri?",
        petunjuk: "Boleh membalik dari posisi telungkup ke terlentang atau dari terlentang ke telungkup tanpa bantuan.",
      },
      {
        no: 3,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Ketika Anda mendudukkan bayi di lantai/tempat tidur tanpa disangga, apakah kepala bayi tetap tegak dan tidak terkulai?",
        petunjuk: "Pegang pinggul/pinggang bayi saat mendudukkan untuk menilai kontrol leher dan kepala.",
      },
      {
        no: 4,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Pada waktu bayi terlentang, apakah ia berusaha meraih mainan yang diacungkan di depan atau di atas dadanya?",
        petunjuk: "Arahkan mainan menarik berwarna cerah di jangkauan tangan bayi.",
      },
      {
        no: 5,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah bayi dapat memindahkan benda atau mainan dari satu tangan ke tangan yang lainnya?",
        petunjuk: "Berikan benda kecil yang aman (seperti kubus/mainan genggam) dan amati proses pemindahan tangan.",
      },
      {
        no: 6,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah bayi dapat memegang mainan atau benda dengan kelima jarinya (menggenggam aktif)?",
        petunjuk: "Amati kekuatan dan respons jemari tangan bayi saat memegang mainan.",
      },
      {
        no: 7,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah bayi dapat mengeluarkan suara gembira bernada tinggi atau menjerit halus saat diajak bermain?",
        petunjuk: "Ekspresi vokal gembira selain menangis saat merasa senang.",
      },
      {
        no: 8,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah bayi menoleh atau mencari sumber suara ketika mendengar panggilan nama atau bunyi mainan di samping/belakangnya?",
        petunjuk: "Panggil nama bayi dari arah samping yang tidak terlihat olehnya.",
      },
      {
        no: 9,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah bayi dapat mengamati dan bermain dengan jari-jari tangan atau kakinya sendiri?",
        petunjuk: "Amati apakah bayi memperhatikan tangannya sendiri atau memasukkan jari kaki/tangan ke mulut.",
      },
      {
        no: 10,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah bayi dapat memegang biskuit dan memasukkannya sendiri ke dalam mulutnya untuk dimakan?",
        petunjuk: "Berikan biskuit bayi dan amati usaha bayi menyuap sendiri.",
      },
    ],
  },
  9: {
    usiaBulan: 9,
    namaGroup: "KPSP Usia 9 Bulan",
    deskripsi: "Untuk bayi usia 9 bulan (rentang 9 - <12 bulan). Terdiri dari 10 pertanyaan perkembangan motorik kasar, motorik halus, bicara/bahasa, serta sosialisasi/kemandirian.",
    pertanyaan: [
      {
        no: 1,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Pada posisi telungkup atau berbaring, apakah bayi dapat bangun dan duduk sendiri tanpa bantuan?",
        petunjuk: "Bayi mampu merubah posisi badannya hingga duduk tegak mandiri.",
      },
      {
        no: 2,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah bayi dapat duduk sendiri secara stabil selama minimal 60 detik tanpa berpegangan atau disangga?",
        petunjuk: "Duduk di lantai tanpa bantuan penyangga tangan atau punggung.",
      },
      {
        no: 3,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah bayi dapat berdiri sendiri dengan berpegangan pada perabot (kursi, meja, atau tempat tidur)?",
        petunjuk: "Bayi menarik dirinya ke atas untuk posisi berdiri dengan pegangan.",
      },
      {
        no: 4,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah bayi dapat memungut benda kecil (seperti remah biskuit) menggunakan ibu jari dan jari telunjuk (pincer grasp)?",
        petunjuk: "Letakkan makanan kecil yang aman di alas datar dan amati cara mengambilnya.",
      },
      {
        no: 5,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah bayi dapat memegang dua kubus atau mainan kecil di masing-masing tangan pada saat yang sama?",
        petunjuk: "Berikan satu mainan di tangan kanan dan satu lagi di tangan kiri tanpa menjatuhkan mainan pertama.",
      },
      {
        no: 6,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah bayi dapat membenturkan dua mainan/kubus yang dipegang di kedua tangannya hingga berbunyi?",
        petunjuk: "Goyangkan atau tepukkan dua kubus di tangan bayi.",
      },
      {
        no: 7,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah bayi dapat mengucapkan suku kata ganda seperti 'da-da', 'ma-ma', 'ba-ba', atau 'pa-pa'?",
        petunjuk: "Suara babbling berulang tanpa harus mengerti artinya.",
      },
      {
        no: 8,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah bayi bereaksi dan menoleh dengan cepat saat namanya dipanggil secara lembut?",
        petunjuk: "Panggil nama bayi dari jarak 1-2 meter.",
      },
      {
        no: 9,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah bayi dapat melambaikan tangan ('da-da') atau bertepuk tangan ('pok-pok-ame') ketika diminta/dicontohkan?",
        petunjuk: "Contohkan gerakan tangan tanpa menyentuh tangan bayi.",
      },
      {
        no: 10,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah bayi menunjukkan rasa cemas/takut pada orang asing yang belum dikenal (stranger anxiety)?",
        petunjuk: "Amati respons saat didekati oleh orang baru/asing.",
      },
    ],
  },
  12: {
    usiaBulan: 12,
    namaGroup: "KPSP Usia 12 Bulan",
    deskripsi: "Untuk anak usia 12 bulan (rentang 12 - <15 bulan). Terdiri dari 10 pertanyaan perkembangan motorik kasar, motorik halus, bicara/bahasa, serta sosialisasi/kemandirian.",
    pertanyaan: [
      {
        no: 1,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Jika Anda memegang salah satu tangan anak saat berdiri, apakah ia dapat berjalan beberapa langkah tanpa jatuh?",
        petunjuk: "Pegang satu tangan anak dan ajak berjalan pelan beberapa langkah.",
      },
      {
        no: 2,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Tanpa berpegangan pada apapun, apakah anak dapat berdiri sendiri dengan stabil selama 30 detik atau lebih?",
        petunjuk: "Posisikan anak berdiri lepas tanpa bantuan dinding/perabot.",
      },
      {
        no: 3,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat membungkuk mengambil mainan di lantai lalu berdiri kembali tanpa berpegangan?",
        petunjuk: "Letakkan mainan menarik di lantai saat anak sedang berdiri lepas.",
      },
      {
        no: 4,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menumpuk 2 kubus atau balok kayu kecil di atas satu sama lain tanpa jatuh?",
        petunjuk: "Berikan 2 kubus kecil dan contohkan cara menumpuknya.",
      },
      {
        no: 5,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat memasukkan benda/kubus kecil ke dalam wadah atau mangkuk secara sengaja?",
        petunjuk: "Beri wadah dan beberapa kubus kecil, minta anak memasukkannya.",
      },
      {
        no: 6,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat memungut benda kecil dengan ibu jari dan ujung jari telunjuk (pincer jepit presisi)?",
        petunjuk: "Amati cara anak mengambil kismis atau remah makanan kecil.",
      },
      {
        no: 7,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat mengucapkan minimal 1 kata bermakna selain 'mama' atau 'papa' (misal: 'dada', 'aus', 'minta')?",
        petunjuk: "Kata spesifik yang konsisten digunakan untuk menunjuk benda/keinginan.",
      },
      {
        no: 8,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak menunjukkan respons mengerti ketika diberi perintah sederhana disertai isyarat (misal: 'berikan ke mama')?",
        petunjuk: "Minta benda yang sedang dipegang anak sambil menadahkan tangan.",
      },
      {
        no: 9,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat menirukan permainan sosial sederhana seperti 'da-da' atau bertepuk tangan?",
        petunjuk: "Amati interaksi anak saat diajak bermain bersama.",
      },
      {
        no: 10,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat memegang cangkir atau gelas sendiri dan mencoba minum darinya (meski sedikit tumpah)?",
        petunjuk: "Berikan cangkir khusus anak berisi sedikit air.",
      },
    ],
  },
  15: {
    usiaBulan: 15,
    namaGroup: "KPSP Usia 15 Bulan",
    deskripsi: "Untuk anak usia 15 bulan (rentang 15 - <18 bulan). Terdiri dari 10 pertanyaan perkembangan motorik kasar, motorik halus, bicara/bahasa, serta sosialisasi/kemandirian.",
    pertanyaan: [
      {
        no: 1,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat berjalan sendiri di dalam ruangan tanpa berpegangan dan tanpa mudah terjatuh?",
        petunjuk: "Anak mampu berjalan mandiri minimal 5-10 langkah.",
      },
      {
        no: 2,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat berjalan mundur 2 hingga 3 langkah secara mandiri?",
        petunjuk: "Amati saat anak menarik mainan dorong/tarik atau saat mundur.",
      },
      {
        no: 3,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat merangkak naik tangga atau naik tangga dengan bantuan pegangan?",
        petunjuk: "Amati kemampuan anak menaiki anak tangga secara aman.",
      },
      {
        no: 4,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menumpuk 3 kubus/balok kayu kecil di atas satu sama lain tanpa runtuh?",
        petunjuk: "Tunjukkan cara membuat menara dari 3 balok kayu.",
      },
      {
        no: 5,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat membuat coretan di atas kertas dengan krayon atau pensil tanpa dibantu?",
        petunjuk: "Berikan krayon dan kertas di atas meja/lantai.",
      },
      {
        no: 6,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat mengeluarkan benda kecil yang ada di dalam botol bening dengan cara membalikkan botol?",
        petunjuk: "Masukkan benda kecil ke dalam botol bening di depan anak.",
      },
      {
        no: 7,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat mengucapkan sedikitnya 3 hingga 6 kata bermakna (misal: 'mimi', 'bapak', 'bola', 'makan')?",
        petunjuk: "Kata bermakna jelas selain kata mama/papa.",
      },
      {
        no: 8,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat menunjuk ke objek yang diinginkannya saat ditanya 'mana bola?' atau 'mana sepatu?'?",
        petunjuk: "Amati gestur menunjuk dengan jari telunjuk.",
      },
      {
        no: 9,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak memperlihatkan atau membawa mainan/benda ke hadapan Anda untuk menunjukkan rasa gembira?",
        petunjuk: "Interaksi berbagi perhatian (joint attention) dengan orang tua.",
      },
      {
        no: 10,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat melepas pakaian sederhana seperti kaus kaki atau topi sendiri?",
        petunjuk: "Amati usaha anak saat mencoba melepas kaus kaki atau topi.",
      },
    ],
  },
  18: {
    usiaBulan: 18,
    namaGroup: "KPSP Usia 18 Bulan",
    deskripsi: "Untuk anak usia 18 bulan (rentang 18 - <24 bulan). Terdiri dari 10 pertanyaan perkembangan motorik kasar, motorik halus, bicara/bahasa, serta sosialisasi/kemandirian.",
    pertanyaan: [
      {
        no: 1,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat berjalan dengan mantap dan cepat tanpa sering terjatuh?",
        petunjuk: "Keseimbangan dan koordinasi berjalan anak sudah baik.",
      },
      {
        no: 2,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat menendang bola kecil ke depan tanpa kehilangan keseimbangan atau berpegangan?",
        petunjuk: "Letakkan bola di depan anak dan minta menendangnya.",
      },
      {
        no: 3,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat naik tangga dengan memegang tangan orang dewasa atau pegangan tangga?",
        petunjuk: "Anak melangkah naik satu per satu anak tangga.",
      },
      {
        no: 4,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menumpuk 4 kubus/balok kayu kecil di atas satu sama lain tanpa jatuh?",
        petunjuk: "Berikan 4 kubus dan ajak menumpuknya menjadi menara.",
      },
      {
        no: 5,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menirukan garis tegak (vertikal) di atas kertas setelah Anda mencontohkannya?",
        petunjuk: "Buat garis lurus tegak di kertas dan minta anak menirunya.",
      },
      {
        no: 6,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat memutar atau membuka tutup wadah/botol sederhana?",
        petunjuk: "Amati eksplorasi tangan anak terhadap botol/toples kecil.",
      },
      {
        no: 7,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat mengucapkan minimal 10 kata yang memiliki arti jelas?",
        petunjuk: "Kosakata aktif anak yang dipahami oleh anggota keluarga.",
      },
      {
        no: 8,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat menunjuk sedikitnya 1 bagian tubuhnya (misal: mata, hidung, telinga) saat diminta?",
        petunjuk: "Tanya 'Mana hidung adik?' tanpa memberi petunjuk isyarat.",
      },
      {
        no: 9,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat memegang sendok dan menyuapkan makanan ke dalam mulutnya sendiri?",
        petunjuk: "Amati saat makan menggunakan sendok anak.",
      },
      {
        no: 10,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak suka menirukan kegiatan rumah tangga sederhana (seperti menyapu, mengelap, atau merapikan benda)?",
        petunjuk: "Anak meniru aktivitas harian orang tua secara spontan.",
      },
    ],
  },
  21: {
    usiaBulan: 21,
    namaGroup: "KPSP Usia 21 Bulan",
    deskripsi: "Untuk anak usia 21 bulan (rentang 21 - <24 bulan). Terdiri dari 10 pertanyaan perkembangan motorik kasar, motorik halus, bicara/bahasa, serta sosialisasi/kemandirian.",
    pertanyaan: [
      {
        no: 1,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat berlari pelan tanpa mudah tersandung atau jatuh?",
        petunjuk: "Amati gerakan lari anak di tempat lapang yang aman.",
      },
      {
        no: 2,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat menaiki tangga dengan menapakkan kedua kaki pada tiap anak tangga (boleh berpegangan)?",
        petunjuk: "Anak naik tangga satu per satu melangkah dengan aman.",
      },
      {
        no: 3,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat melempar bola kecil ke arah depan dengan ayunan tangan?",
        petunjuk: "Berikan bola plastik/tenis dan minta anak melemparnya ke depan.",
      },
      {
        no: 4,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menumpuk 5 kubus/balok kayu kecil di atas satu sama lain tanpa jatuh?",
        petunjuk: "Demonstrasikan menara dari 5 kubus kayu kecil.",
      },
      {
        no: 5,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat membalik halaman buku satu per satu (atau 1-2 lembar sekaligus)?",
        petunjuk: "Berikan buku cerita bergambar dengan halaman tebal.",
      },
      {
        no: 6,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat memindahkan cairan atau benda kecil dari satu wadah ke wadah lain tanpa banyak tumpah?",
        petunjuk: "Amati saat anak bermain air atau memindahkan biji-bijian/mainan.",
      },
      {
        no: 7,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat menggabungkan 2 kata bermakna menjadi satu frasa (misal: 'minta minum', 'mama ikut', 'mau makan')?",
        petunjuk: "Dua kata terpisah yang diucapkan berurutan membentuk arti.",
      },
      {
        no: 8,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat menunjuk sedikitnya 3 bagian tubuhnya saat Anda sebutkan namanya?",
        petunjuk: "Tanyakan posisi mata, telinga, mulut, atau kaki tanpa menunjuk duluan.",
      },
      {
        no: 9,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat makan sendiri menggunakan sendok tanpa banyak makanan tumpah?",
        petunjuk: "Makan mandiri dengan kontrol gerakan tangan yang cukup rapi.",
      },
      {
        no: 10,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat memberitahu atau menunjukkan keinginan ketika ingin buang air (ompol/pup)?",
        petunjuk: "Menggunakan isyarat kata atau menunjuk celana saat merasa tidak nyaman.",
      },
    ],
  },
  24: {
    usiaBulan: 24,
    namaGroup: "KPSP Usia 24 Bulan",
    deskripsi: "Untuk anak usia 24 bulan (rentang 24 - <30 bulan). Terdiri dari 10 pertanyaan perkembangan motorik kasar, motorik halus, bicara/bahasa, serta sosialisasi/kemandirian.",
    pertanyaan: [
      {
        no: 1,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat melompat dengan kedua kaki terangkat bersamaan dari lantai?",
        petunjuk: "Minta anak melompat di tempat di atas lantai rata.",
      },
      {
        no: 2,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat menendang bola besar ke depan tanpa kehilangan keseimbangan atau berpegangan?",
        petunjuk: "Letakkan bola di depan anak dan minta menendang kuat.",
      },
      {
        no: 3,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat berjalan turun tangga dengan menapakkan kedua kaki di tiap anak tangga?",
        petunjuk: "Boleh memegang pegangan tangga atau dinding saat turun.",
      },
      {
        no: 4,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menumpuk 6 kubus/balok kayu kecil di atas satu sama lain tanpa jatuh?",
        petunjuk: "Beri 6 kubus kayu dan ajak membuat menara tinggi.",
      },
      {
        no: 5,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menirukan garis mendatar (horisontal) atau lingkaran setelah ditunjukkan?",
        petunjuk: "Buat contoh garis mendatar di kertas dan minta anak menirunya.",
      },
      {
        no: 6,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat memutar dan membuka tutup botol berulir atau gagang pintu?",
        petunjuk: "Menggunakan gerakan pergelangan tangan memutar.",
      },
      {
        no: 7,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat menyebutkan nama minimal 2 gambar objek/hewan yang umum saat Anda tunjukkan?",
        petunjuk: "Tunjukkan gambar kucing, anjing, mobil, bola, atau bunga.",
      },
      {
        no: 8,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat memahami dan melaksanakan 2 perintah berurutan (misal: 'ambil bola itu lalu taruh di meja')?",
        petunjuk: "Berikan perintah dua tahap tanpa bantuan isyarat berulang.",
      },
      {
        no: 9,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat melepas pakaian atau celana sendiri yang longgar tanpa bantuan?",
        petunjuk: "Latihan kemandirian melepas pakaian/celana karet.",
      },
      {
        no: 10,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat mencuci dan mengeringkan tangannya sendiri (dengan sedikit bantuan)?",
        petunjuk: "Pengenalan kebiasaan cuci tangan mandiri.",
      },
    ],
  },
  30: {
    usiaBulan: 30,
    namaGroup: "KPSP Usia 30 Bulan",
    deskripsi: "Untuk anak usia 30 bulan (rentang 30 - <36 bulan). Terdiri dari 10 pertanyaan perkembangan motorik kasar, motorik halus, bicara/bahasa, serta sosialisasi/kemandirian.",
    pertanyaan: [
      {
        no: 1,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat berjalan naik tangga sendiri secara mandiri (setiap langkah menapak anak tangga)?",
        petunjuk: "Anak dapat naik tangga tanpa perlu dipegangi tangannya.",
      },
      {
        no: 2,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat berdiri di atas satu kaki selama 1 hingga 2 detik tanpa berpegangan?",
        petunjuk: "Contohkan mengangkat satu kaki dan minta anak menirukan.",
      },
      {
        no: 3,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Tanpa berpegangan, apakah anak dapat menendang bola kecil ke arah depan dengan ayunan kaki yang baik?",
        petunjuk: "Letakkan bola kecil di depan anak saat berdiri bebas.",
      },
      {
        no: 4,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menumpuk 6 hingga 8 kubus/balok kayu kecil menjadi menara tanpa jatuh?",
        petunjuk: "Sediakan kubus kayu dan amati tinggi menara yang dibuat.",
      },
      {
        no: 5,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menirukan gambar lingkaran yang tertutup rapat di atas kertas?",
        petunjuk: "Gambarkan lingkaran dan minta anak menirukannya di kertas.",
      },
      {
        no: 6,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat mencuci dan mengeringkan kedua tangannya sendiri setelah selesai makan/bermain?",
        petunjuk: "Bisa menggunakan sabun dan mengeringkan dengan handuk.",
      },
      {
        no: 7,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat menyebutkan sedikitnya 1 nama teman bermain atau anggota keluarga selain orang tua?",
        petunjuk: "Tanyakan nama teman, nenek, paman, atau saudara.",
      },
      {
        no: 8,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat menyebutkan nama minimal 3 gambar objek yang Anda tunjukkan di dalam buku?",
        petunjuk: "Gunakan buku cerita atau kartu bergambar objek harian.",
      },
      {
        no: 9,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat memakai celana sendiri (celana pendek/panjang karet) tanpa dibantu?",
        petunjuk: "Anak menarik celana sendiri hingga ke pinggang.",
      },
      {
        no: 10,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat menyebutkan nama dirinya secara lengkap atau nama panggilannya saat ditanya?",
        petunjuk: "Tanyakan 'Siapa nama adik?'.",
      },
    ],
  },
  36: {
    usiaBulan: 36,
    namaGroup: "KPSP Usia 36 Bulan",
    deskripsi: "Untuk anak usia 36 bulan (rentang 36 - <42 bulan). Terdiri dari 10 pertanyaan perkembangan motorik kasar, motorik halus, bicara/bahasa, serta sosialisasi/kemandirian.",
    pertanyaan: [
      {
        no: 1,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat melompat melewati lembar kertas di lantai dengan kedua kaki terangkat bersamaan?",
        petunjuk: "Letakkan selembar kertas di lantai dan minta anak melompatinya.",
      },
      {
        no: 2,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat naik tangga dengan melangkahkan kaki bergantian (satu kaki per anak tangga) tanpa berpegangan?",
        petunjuk: "Amati cara melangkah saat naik tangga.",
      },
      {
        no: 3,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat mengayuh sepeda roda tiga sejauh sedikitnya 3 meter ke depan?",
        petunjuk: "Gunakan sepeda roda tiga anak.",
      },
      {
        no: 4,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menumpuk 8 kubus/balok kayu kecil satu per satu tanpa runtuh?",
        petunjuk: "Uji konsentrasi dan keseimbangan tangan anak.",
      },
      {
        no: 5,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menirukan gambar tanda silang (+) di atas kertas setelah Anda mencontohkannya?",
        petunjuk: "Buat dua garis saling memotong (+) dan ajak anak menirunya.",
      },
      {
        no: 6,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menggambar garis lurus sejajar di atas kertas?",
        petunjuk: "Tunjukkan cara menarik garis lurus.",
      },
      {
        no: 7,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak mengerti konsep kata depan seperti 'di atas', 'di bawah', dan 'di dalam'?",
        petunjuk: "Minta taruh mainan di atas meja atau di bawah kursi.",
      },
      {
        no: 8,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah orang asing (bukan keluarga dekat) dapat memahami sebagian besar kata/kalimat yang diucapkan anak?",
        petunjuk: "Kejelasannya dapat dipahami oleh tetangga/tamu.",
      },
      {
        no: 9,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat bermain bersama teman secara interaktif (misal: berbagi mainan atau kejar-kejaran)?",
        petunjuk: "Bukan sekadar bermain berdampingan (parallel play).",
      },
      {
        no: 10,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat mengenakan kaus/baju sendiri tanpa bantuan (kecuali mengancingkan)?",
        petunjuk: "Memasukkan kepala dan kedua lengan ke dalam baju.",
      },
    ],
  },
  42: {
    usiaBulan: 42,
    namaGroup: "KPSP Usia 42 Bulan",
    deskripsi: "Untuk anak usia 42 bulan (rentang 42 - <48 bulan). Terdiri dari 10 pertanyaan perkembangan motorik kasar, motorik halus, bicara/bahasa, serta sosialisasi/kemandirian.",
    pertanyaan: [
      {
        no: 1,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat melompat dengan satu kaki berturut-turut minimal 2 hingga 3 kali tanpa jatuh?",
        petunjuk: "Minta anak melompat dengan satu kaki (engklek).",
      },
      {
        no: 2,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat menangkap bola besar yang dilemparkan dari jarak 1 meter dengan kedua tangannya?",
        petunjuk: "Lempar bola plastik/karet sedang pelan ke arah dada anak.",
      },
      {
        no: 3,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat berdiri di atas satu kaki selama minimal 3 detik tanpa berpegangan?",
        petunjuk: "Hitung 'satu, dua, tiga' saat anak berdiri satu kaki.",
      },
      {
        no: 4,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menggunting kertas menjadi 2 bagian secara mandiri menggunakan gunting anak?",
        petunjuk: "Berikan gunting tumpul khusus anak dan selembar kertas.",
      },
      {
        no: 5,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menggambar bentuk orang dengan minimal 2 bagian tubuh (misal: kepala dan kaki/tangan)?",
        petunjuk: "Berikan kertas dan krayon, Minta menggambar gambar orang.",
      },
      {
        no: 6,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat meronce/memasukkan manik-manik besar ke dalam tali secara mandiri?",
        petunjuk: "Sediakan tali dan 3-4 manik-manik berlubang besar.",
      },
      {
        no: 7,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat menyebutkan nama minimal 4 warna dasar (merah, kuning, hijau, biru) dengan benar?",
        petunjuk: "Tunjukkan objek bermacam warna dan tanya warnanya.",
      },
      {
        no: 8,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat menjawab dengan benar jika ditanya: 'Apa yang kamu lakukan jika kamu merasa lapar/aus/lelah'?",
        petunjuk: "Jawaban yang logis seperti: makan, minum, tidur/istirahat.",
      },
      {
        no: 9,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat memakai sepatu sendiri (tanpa perlu mengikat tali sepatu)?",
        petunjuk: "Sepatu selop atau berperekat (velcro).",
      },
      {
        no: 10,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat mengenakan celana dan baju sendiri secara rapi tanpa bantuan?",
        petunjuk: "Latihan berpakaian mandiri.",
      },
    ],
  },
  48: {
    usiaBulan: 48,
    namaGroup: "KPSP Usia 48 Bulan",
    deskripsi: "Untuk anak usia 48 bulan (rentang 48 - <54 bulan). Terdiri dari 10 pertanyaan perkembangan motorik kasar, motorik halus, bicara/bahasa, serta sosialisasi/kemandirian.",
    pertanyaan: [
      {
        no: 1,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat berdiri di atas satu kaki selama minimal 6 detik tanpa berpegangan dan tanpa goyah?",
        petunjuk: "Hitung hingga 6 detik saat anak berdiri dengan satu kaki.",
      },
      {
        no: 2,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat melompat dengan satu kaki sejauh 1 hingga 2 meter (melompat engklek)?",
        petunjuk: "Amati kelincahan dan keseimbangan melompat satu kaki.",
      },
      {
        no: 3,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat melempar bola kecil ke atas atau ke depan secara terarah menggunakan satu tangan?",
        petunjuk: "Lempar bola tennis/plastik ke sasaran terdekat.",
      },
      {
        no: 4,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat meniru menggambar bentuk persegi / kotak (4 sisi lurus) setelah Anda contohkan?",
        petunjuk: "Gambarkan bentuk kotak di kertas dan minta anak menirunya.",
      },
      {
        no: 5,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menggambar gambar orang dengan sedikitnya 3 bagian tubuh (kepala, badan, tangan/kaki)?",
        petunjuk: "Amati detail gambar orang yang dibuat anak.",
      },
      {
        no: 6,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat mengancingkan baju sendiri pada sedikitnya 2 hingga 3 kancing?",
        petunjuk: "Amati koordinasi jari tangan saat memasukkan kancing baju.",
      },
      {
        no: 7,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat berbicara menggunakan kalimat lengkap berisi 4 hingga 5 kata yang jelas?",
        petunjuk: "Misal: 'Aku mau main bola di luar'.",
      },
      {
        no: 8,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak memahami lawan kata sederhana (misal: 'gajah itu besar, tikus itu...', 'es itu dingin, api itu...')?",
        petunjuk: "Tanyakan kelanjutan kalimat lawan kata tersebut.",
      },
      {
        no: 9,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat pergi ke toilet sendiri, melepaskan celana, dan memakai celananya kembali secara mandiri?",
        petunjuk: "Kemandirian saat toilet training (toilet-use).",
      },
      {
        no: 10,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat menggosok gigi sendiri dengan bantuan minimal dari orang tua?",
        petunjuk: "Anak memegang sikat gigi dan menyikat giginya.",
      },
    ],
  },
  54: {
    usiaBulan: 54,
    namaGroup: "KPSP Usia 54 Bulan",
    deskripsi: "Untuk anak usia 54 bulan (rentang 54 - <60 bulan). Terdiri dari 10 pertanyaan perkembangan motorik kasar, motorik halus, bicara/bahasa, serta sosialisasi/kemandirian.",
    pertanyaan: [
      {
        no: 1,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat berdiri di atas satu kaki selama 6 detik atau lebih tanpa berpegangan atau terjatuh?",
        petunjuk: "Minta anak berdiri satu kaki dan hitung 1 hingga 6 detik.",
      },
      {
        no: 2,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat melompat dengan satu kaki (engklek) 2 hingga 3 kali berturut-turut tanpa hilang keseimbangan?",
        petunjuk: "Minta anak melompat engklek di lantai datar.",
      },
      {
        no: 3,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat menangkap bola kasti atau bola kecil yang dilemparkan dari jarak 1,5 meter dengan kedua tangannya?",
        petunjuk: "Lempar bola pelan sejajar dada dari jarak 1,5 meter.",
      },
      {
        no: 4,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menggambar bentuk orang dengan sedikitnya 3 bagian tubuh (kepala, badan, kaki/tangan)?",
        petunjuk: "Berikan kertas dan krayon, minta menggambar gambar orang.",
      },
      {
        no: 5,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menggunting kertas lurus sepanjang 10 cm menggunakan gunting anak?",
        petunjuk: "Buat garis lurus di kertas dan minta anak menggunting mengikuti garis.",
      },
      {
        no: 6,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat meniru menggambar bentuk persegi / kotak setelah contoh diberikan?",
        petunjuk: "Gambarkan bentuk kotak di kertas dan minta anak menirunya.",
      },
      {
        no: 7,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak berbicara menggunakan kalimat lengkap (4-5 kata) yang mudah dipahami oleh orang luar?",
        petunjuk: "Kalimat terstruktur jelas dan artikulasi cukup bersih.",
      },
      {
        no: 8,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat menjawab kegunaan dari benda harian (misal: 'sendok untuk apa?', 'cangkir untuk apa?')?",
        petunjuk: "Jawaban yang logis (untuk makan, untuk minum).",
      },
      {
        no: 9,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat memakai baju atau kaos sendiri tanpa bantuan?",
        petunjuk: "Anak dapat memasukkan kepala dan tangan sendiri dengan rapi.",
      },
      {
        no: 10,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat mengancingkan sedikitnya 2-3 kancing baju atau kancing celananya sendiri?",
        petunjuk: "Amati kemampuan motorik halus saat mengancingkan baju.",
      },
    ],
  },
  60: {
    usiaBulan: 60,
    namaGroup: "KPSP Usia 60 Bulan",
    deskripsi: "Untuk anak usia 60 bulan (rentang 60 - <66 bulan). Terdiri dari 10 pertanyaan perkembangan motorik kasar, motorik halus, bicara/bahasa, serta sosialisasi/kemandirian.",
    pertanyaan: [
      {
        no: 1,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat berdiri di atas satu kaki selama 10 detik atau lebih tanpa berpegangan?",
        petunjuk: "Hitung hingga 10 detik saat anak berdiri satu kaki.",
      },
      {
        no: 2,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat melompat dengan satu kaki sejauh 2 hingga 3 meter tanpa terjatuh?",
        petunjuk: "Uji ketangkasan melompat engklek berpindah tempat.",
      },
      {
        no: 3,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat berjalan jinjit di atas garis lurus sepanjang 2 meter tanpa oleng?",
        petunjuk: "Buat garis di lantai dan minta anak berjalan dengan tumit terangkat.",
      },
      {
        no: 4,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat meniru menggambar bentuk segitiga (3 sisi lurus) setelah Anda contohkan?",
        petunjuk: "Gambarkan segitiga dan minta anak menirunya di kertas.",
      },
      {
        no: 5,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menggambar gambar orang lengkap dengan sedikitnya 6 bagian tubuh?",
        petunjuk: "Bagian tubuh mencakup: kepala, mata, hidung, mulut, badan, tangan, atau kaki.",
      },
      {
        no: 6,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menulis atau meniru tulisan beberapa huruf atau angka sederhana?",
        petunjuk: "Menulis huruf/angka seperti 'A', 'B', '1', '2'.",
      },
      {
        no: 7,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat menyebutkan nama sedikitnya 4 warna dasar (merah, hijau, kuning, biru) dengan tepat?",
        petunjuk: "Tunjukkan objek bermacam warna secara acak.",
      },
      {
        no: 8,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat menceritakan peristiwa pendek atau cerita bergambar dengan kalimat teratur?",
        petunjuk: "Anak dapat bercerita tentang pengalamannya di sekolah/taman.",
      },
      {
        no: 9,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat berpakaian sendiri secara lengkap dari baju hingga celana tanpa dibantu?",
        petunjuk: "Kemandirian penuh saat berganti pakaian.",
      },
      {
        no: 10,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat mengikuti aturan dalam permainan kelompok (seperti petak pêtet atau ular tangga)?",
        petunjuk: "Mampu mengerti konsep giliran dan aturan main bersama teman.",
      },
    ],
  },
  66: {
    usiaBulan: 66,
    namaGroup: "KPSP Usia 66 Bulan",
    deskripsi: "Untuk anak usia 66 bulan (rentang 66 - <72 bulan). Terdiri dari 10 pertanyaan perkembangan motorik kasar, motorik halus, bicara/bahasa, serta sosialisasi/kemandirian.",
    pertanyaan: [
      {
        no: 1,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat berjalan dengan tumit berjinjit sejauh 3 meter berturut-turut secara seimbang?",
        petunjuk: "Amati kestabilan berjalan jinjit anak.",
      },
      {
        no: 2,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat menangkap bola kasti yang memantul dari lantai menggunakan kedua tangan?",
        petunjuk: "Pantulkan bola ke lantai ke arah anak.",
      },
      {
        no: 3,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat melompati rintangan kecil setinggi 10-15 cm dengan kedua kaki bersamaan?",
        petunjuk: "Letakkan balok/buku kecil sebagai rintangan.",
      },
      {
        no: 4,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat meniru menggambar bentuk belah ketupat atau pola geometris dengan rapi?",
        petunjuk: "Gambarkan bentuk belah ketupat di kertas.",
      },
      {
        no: 5,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat mengikat tali sepatu atau membuat ikatan simpul sederhana sendiri?",
        petunjuk: "Uji koordinasi tali sepatu atau pita.",
      },
      {
        no: 6,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menggunting bentuk lingkaran atau melengkung dari kertas secara teratur?",
        petunjuk: "Gambarkan lingkaran di kertas dan minta anak mengguntingnya.",
      },
      {
        no: 7,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak memahami pertanyaan sebab-akibat (misal: 'Mengapa kita harus cuci tangan sebelum makan?')?",
        petunjuk: "Jawaban yang menunjukkan pemahaman alasan/sebab.",
      },
      {
        no: 8,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat menyebutkan nama hari-hari dalam seminggu atau urutan waktu (pagi, siang, malam)?",
        petunjuk: "Paham urutan waktu harian.",
      },
      {
        no: 9,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat menghitung secara urut minimal 5 hingga 10 benda nyata (misal: hitung kelereng/pensil)?",
        petunjuk: "Menunjuk benda satu per satu sambil menyebutkan angkanya.",
      },
      {
        no: 10,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat mandi sendiri dan membersihkan badannya tanpa perlu disikatkan oleh orang tua?",
        petunjuk: "Kemandirian saat mandi harian.",
      },
    ],
  },
  72: {
    usiaBulan: 72,
    namaGroup: "KPSP Usia 72 Bulan",
    deskripsi: "Untuk anak usia 72 bulan (usia 6 tahun). Terdiri dari 10 pertanyaan perkembangan motorik kasar, motorik halus, bicara/bahasa, serta sosialisasi/kemandirian.",
    pertanyaan: [
      {
        no: 1,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat berdiri di atas satu kaki selama 10-15 detik dengan mata tertutup tanpa terjatuh?",
        petunjuk: "Minta anak memejamkan mata dan berdiri satu kaki.",
      },
      {
        no: 2,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat berjalan meniti garis lurus dengan tumit menyentuh ujung jari kaki (tandem walk)?",
        petunjuk: "Berjalan menyusuri garis lurus rapat dari tumit ke jari.",
      },
      {
        no: 3,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat melompat engklek 5 hingga 6 kali berturut-turut tanpa kehilangan keseimbangan?",
        petunjuk: "Uji keseimbangan dan kekuatan kaki dominan.",
      },
      {
        no: 4,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menuliskan nama panggilannya sendiri di atas kertas secara jelas?",
        petunjuk: "Kemampuan menulis nama sendiri secara mandiri.",
      },
      {
        no: 5,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menggambar gambar orang lengkap dengan pakaian, rambut, dan detail anggota tubuh?",
        petunjuk: "Detail gambar orang mencakup pakaian dan fitur lengkap.",
      },
      {
        no: 6,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat meniru menggambar bentuk kubus 3 dimensi atau bangun datar berurutan?",
        petunjuk: "Gambarkan bentuk kotak/kubus dan amati tiruan anak.",
      },
      {
        no: 7,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat menjelaskan arti atau fungsi dari sedikitnya 5 benda yang umum di sekitarnya?",
        petunjuk: "Menjelaskan dengan kalimatnya sendiri secara baik.",
      },
      {
        no: 8,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak mengerti konsep jumlah dan instruksi berhitung (misal: 'Ambilkan 5 sendok di atas meja')?",
        petunjuk: "Mengambil jumlah benda tepat sesuai permintaan.",
      },
      {
        no: 9,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat berpakaian, melepaskan, dan merapikan pakaiannya sendiri secara mandiri?",
        petunjuk: "Kemandirian penuh dalam berbusana dan merapikan barang diri.",
      },
      {
        no: 10,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak menunjukkan sikap sopan, mau berbagi, dan mampu mengendalikan emosi saat bermain bersama kelompok?",
        petunjuk: "Kematangan sosialisasi persiapan masuk sekolah dasar.",
      },
    ],
  },
};

export function hitungKpsp(jawaban: Record<number, KpspJawaban>): KpspHasil {
  let totalYa = 0;
  let totalTidak = 0;

  Object.values(jawaban).forEach((v) => {
    if (v === "ya") totalYa++;
    if (v === "tidak") totalTidak++;
  });

  if (totalYa >= 9) {
    return {
      totalYa,
      totalTidak,
      kategori: "sesuai",
      label: "Perkembangan Sesuai Umur (S)",
      saran: "Perkembangan anak sesuai dengan usianya (9–10 'YA'). Beri pujian pada ibu/pengasuh. Teruskan pola asuh dan berikan stimulasi tumbuh kembang sesuai kelompok umur. Lakukan jadwal skrining KPSP berikutnya saat usia 6 bulan.",
    };
  }

  if (totalYa >= 7) {
    return {
      totalYa,
      totalTidak,
      kategori: "meragukan",
      label: "Perkembangan Meragukan (M)",
      saran: "Perkembangan anak tergolong meragukan (7–8 'YA'). Anjurkan ibu/pengasuh untuk memberikan stimulasi lebih sering dan intensif, terutama pada sektor yang belum dijawab 'YA'. Lakukan evaluasi & skrining ulang KPSP dalam 2 minggu ke depan.",
    };
  }

  return {
    totalYa,
    totalTidak,
    kategori: "penyimpangan",
    label: "Kemungkinan Penyimpangan Perkembangan (P)",
    saran: "Kemungkinan terdapat penyimpangan perkembangan (<= 6 'YA'). Segera rujuk anak ke Fasilitas Kesehatan Rujukan (Klinik Tumbuh Kembang / Dokter Spesialis Anak) untuk evaluasi diagnostik serta penanganan intervensi dini komprehensif.",
  };
}

export function sektorTerabaikan(
  pertanyaanList: KpspQuestion[],
  jawaban: Record<number, KpspJawaban>
): KpspQuestion[] {
  return pertanyaanList.filter((q) => jawaban[q.no] === "tidak");
}
