export type KpspSektor = "kasar" | "halus" | "bicara" | "sosialisasi";

export interface KpspQuestion {
  no: number;
  sektor: KpspSektor;
  sektorLabel: string;
  teks: string;
  petunjuk?: string;
}

export interface KpspAgeGroup {
  usiaBulan: number;
  namaGroup: string;
  deskripsi: string;
  pertanyaan: KpspQuestion[];
}

export type KpspJawaban = "ya" | "tidak" | null;

export interface KpspHasil {
  totalYa: number;
  totalTidak: number;
  kategori: "sesuai" | "meragukan" | "penyimpangan";
  label: string;
  saran: string;
}

export const KPSP_DATA: Record<number, KpspAgeGroup> = {
  3: {
    usiaBulan: 3,
    namaGroup: "KPSP Usia 3 Bulan",
    deskripsi: "Untuk bayi usia 3 bulan (rentang 3 - <6 bulan). Kuesioner resmi Kemenkes RI SDIDTK terdiri dari 10 pertanyaan tervalidasi.",
    pertanyaan: [
      {
        no: 1,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Pada waktu bayi telungkup di alas yang rata, apakah ia dapat mengangkat kepalanya?",
        petunjuk: "Posisikan bayi telungkup di tempat tidur atau alas datar yang aman.",
      },
      {
        no: 2,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Pada waktu bayi telungkup di alas yang rata, apakah ia dapat mengangkat kepalanya sampai setinggi 45 derajat?",
        petunjuk: "Kepala dan dada bagian atas terangkat dari alas datar.",
      },
      {
        no: 3,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Pada waktu bayi telungkup di alas yang rata, apakah ia dapat mengangkat kepalanya sampai setinggi 90 derajat?",
        petunjuk: "Kepala tegak lurus dan dada terangkat dari alas.",
      },
      {
        no: 4,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Pada waktu bayi telungkup di alas yang rata, apakah ia dapat mengangkat kepalanya 45 derajat dengan menumpu pada lengan bawah?",
        petunjuk: "Menahan beban dada bagian atas menggunakan kedua lengan bawah/siku.",
      },
      {
        no: 5,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Pada waktu bayi terlentang, apakah masing-masing lengan dan tungkainya bergerak dengan bebas?",
        petunjuk: "Amati gerakan tangan dan kaki kanan serta kiri saat bayi tenang/gembira.",
      },
      {
        no: 6,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Pada waktu bayi terlentang, apakah ia dapat menatap mata Anda?",
        petunjuk: "Tatap wajah bayi dari jarak kurang lebih 20–30 cm.",
      },
      {
        no: 7,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah bayi dapat mengeluarkan suara-suara lain (ngoceh), selain menangis?",
        petunjuk: "Dengarkan ocehan vokal spontan (seperti 'ooh', 'aah') saat diajak bicara.",
      },
      {
        no: 8,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Pada waktu bayi terlentang, apakah ia dapat mengikuti gerakan Anda dengan menggerakkan kepalanya dari salah satu sisi hampir sampai ke tengah?",
        petunjuk: "Gerakkan mainan berwarna cerah perlahan dari samping ke arah tengah.",
      },
      {
        no: 9,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Pada waktu bayi terlentang, apakah ia dapat mengikuti gerakan Anda dengan menggerakkan kepalanya dari satu sisi ke sisi lain?",
        petunjuk: "Gerakkan mainan perlahan melintasi pandangan bayi dari kiri ke kanan (180 derajat).",
      },
      {
        no: 10,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah bayi tersenyum ketika Anda mengajak tersenyum/berbicara?",
        petunjuk: "Ajak bayi tersenyum dan bicara ramah di depannya.",
      },
    ],
  },
  6: {
    usiaBulan: 6,
    namaGroup: "KPSP Usia 6 Bulan",
    deskripsi: "Untuk bayi usia 6 bulan (rentang 6 - <9 bulan). Kuesioner resmi Kemenkes RI SDIDTK terdiri dari 10 pertanyaan tervalidasi.",
    pertanyaan: [
      {
        no: 1,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Pada waktu bayi telungkup di alas yang rata, apakah ia dapat mengangkat kepala dengan dada terangkat dan menumpu pada kedua tangannya?",
        petunjuk: "Dada terangkat dari alas datar, beban ditumpu dengan telapak tangan/lengan lurus.",
      },
      {
        no: 2,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah bayi dapat membalikkan badannya dari telungkup ke terlentang atau sebaliknya?",
        petunjuk: "Boleh membalik dari telungkup ke terlentang atau sebaliknya tanpa bantuan.",
      },
      {
        no: 3,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Pada waktu bayi terlentang, apakah ia dapat mempertahankan kepalanya tetap tegak dan tidak terkulai saat Anda mendudukkannya?",
        petunjuk: "Pegang tangan/pinggul bayi saat mendudukkan untuk menilai kontrol leher.",
      },
      {
        no: 4,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Pada waktu bayi terlentang, apakah ia berusaha meraih mainan yang diacungkan di depan atau di atas dadanya?",
        petunjuk: "Arahkan mainan menarik berwarna cerah di jangkauan tangan bayi.",
      },
      {
        no: 5,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah bayi dapat memindahkan mainan dari satu tangan ke tangan yang lain?",
        petunjuk: "Berikan benda kecil yang aman dan amati pemindahan dari tangan kanan ke kiri.",
      },
      {
        no: 6,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah bayi dapat memegang mainan atau benda kecil dengan ibu jari dan jari-jarinya (menggenggam)?",
        petunjuk: "Amati kekuatan dan kontrol jemari tangan saat memegang mainan.",
      },
      {
        no: 7,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah bayi dapat mengeluarkan suara gembira bernada tinggi atau menjerit?",
        petunjuk: "Ekspresi vokal gembira saat merasa senang saat diajak bermain.",
      },
      {
        no: 8,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah bayi tersenyum ketika melihat mainan yang menarik atau gambar di cermin?",
        petunjuk: "Amati respons senyum gembira terhadap cermin atau mainan.",
      },
      {
        no: 9,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah bayi berpaling ke arah suara bila Anda memanggil namanya dari belakang/samping?",
        petunjuk: "Panggil nama bayi dari samping/belakang tanpa terlihat langsung.",
      },
      {
        no: 10,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah bayi dapat makan biskuit sendiri tanpa dibantu?",
        petunjuk: "Berikan biskuit bayi dan amati usaha bayi menyuap sendiri ke mulut.",
      },
    ],
  },
  9: {
    usiaBulan: 9,
    namaGroup: "KPSP Usia 9 Bulan",
    deskripsi: "Untuk bayi usia 9 bulan (rentang 9 - <12 bulan). Kuesioner resmi Kemenkes RI SDIDTK terdiri dari 10 pertanyaan tervalidasi.",
    pertanyaan: [
      {
        no: 1,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Pada posisi telungkup, apakah bayi dapat bangun sendiri sampai posisi duduk?",
        petunjuk: "Bayi mampu merubah posisi badannya dari berbaring/telungkup hingga duduk tegak mandiri.",
      },
      {
        no: 2,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah bayi dapat duduk sendiri tanpa disangga selama 60 detik?",
        petunjuk: "Duduk di lantai tanpa bantuan penyangga tangan atau punggung.",
      },
      {
        no: 3,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah bayi dapat berdiri dengan berpegangan pada perabot atau kursi?",
        petunjuk: "Bayi menarik dirinya ke atas untuk posisi berdiri dengan pegangan perabot.",
      },
      {
        no: 4,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah bayi dapat memindahkan kubus/mainan dari satu tangan ke tangan yang lain?",
        petunjuk: "Amati proses memindahkan kubus/mainan antar tangan.",
      },
      {
        no: 5,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah bayi dapat mengambil benda kecil seperti kismis/remah makanan dengan ibu jari dan jari telunjuk (penjepit pincer)?",
        petunjuk: "Letakkan makanan kecil di alas datar dan amati jepitan jemarinya.",
      },
      {
        no: 6,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah bayi dapat memegang dua kubus di masing-masing tangan pada saat yang sama?",
        petunjuk: "Beri satu kubus di tangan kanan dan satu lagi di tangan kiri tanpa menjatuhkan kubus pertama.",
      },
      {
        no: 7,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah bayi dapat mengucapkan suku kata ganda seperti 'da-da', 'ma-ma', 'ba-ba'?",
        petunjuk: "Ocehan vokal ganda berulang tanpa harus sempurna artinya.",
      },
      {
        no: 8,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah bayi menoleh saat dipanggil namanya dari belakang?",
        petunjuk: "Panggil nama bayi dari jarak 1-2 meter dari arah belakang.",
      },
      {
        no: 9,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah bayi dapat bertepuk tangan atau melambaikan tangan ('da-da')?",
        petunjuk: "Contohkan gerakan tangan tanpa memegang tangan bayi.",
      },
      {
        no: 10,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah bayi dapat makan biskuit sendiri?",
        petunjuk: "Amati usaha memegang dan memasukkan biskuit ke mulut secara mandiri.",
      },
    ],
  },
  12: {
    usiaBulan: 12,
    namaGroup: "KPSP Usia 12 Bulan",
    deskripsi: "Untuk anak usia 12 bulan (rentang 12 - <15 bulan). Kuesioner resmi Kemenkes RI SDIDTK terdiri dari 10 pertanyaan tervalidasi.",
    pertanyaan: [
      {
        no: 1,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Jika Anda memegang kedua tangannya, apakah ia dapat berjalan beberapa langkah?",
        petunjuk: "Pegang kedua tangan anak dan ajak berjalan beberapa langkah.",
      },
      {
        no: 2,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat berdiri sendiri tanpa berpegangan selama 30 detik atau lebih?",
        petunjuk: "Posisikan anak berdiri lepas tanpa bantuan dinding/perabot.",
      },
      {
        no: 3,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat membungkuk mengambil mainan di lantai lalu berdiri kembali tanpa berpegangan?",
        petunjuk: "Letakkan mainan di lantai saat anak berdiri lepas.",
      },
      {
        no: 4,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menumpuk 2 kubus/balok kayu di atas satu sama lain tanpa jatuh?",
        petunjuk: "Berikan 2 kubus kecil dan contohkan cara menumpuknya.",
      },
      {
        no: 5,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat memasukkan benda/kubus ke dalam wadah atau mangkuk?",
        petunjuk: "Beri wadah dan beberapa kubus, minta anak memasukkannya.",
      },
      {
        no: 6,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat memungut benda kecil dengan ibu jari dan ujung jari telunjuk (pincer jepit presisi)?",
        petunjuk: "Amati jepitan presisi ujung jari anak.",
      },
      {
        no: 7,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat mengucapkan minimal 1 kata bermakna selain 'mama' atau 'papa'?",
        petunjuk: "Kata spesifik yang konsisten digunakan untuk menunjuk benda/keinginan.",
      },
      {
        no: 8,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak mengerti perintah sederhana tanpa isyarat seperti 'berikan mainan itu'?",
        petunjuk: "Minta benda tanpa bantuan gerakan tangan/isyarat tubuh.",
      },
      {
        no: 9,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat menirukan permainan sosial seperti 'da-da' atau bertepuk tangan?",
        petunjuk: "Amati interaksi tiruan saat diajak bermain bersama.",
      },
      {
        no: 10,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat minum sendiri dari cangkir/gelas tanpa banyak tumpah?",
        petunjuk: "Berikan cangkir khusus anak berisi sedikit air.",
      },
    ],
  },
  15: {
    usiaBulan: 15,
    namaGroup: "KPSP Usia 15 Bulan",
    deskripsi: "Untuk anak usia 15 bulan (rentang 15 - <18 bulan). Kuesioner resmi Kemenkes RI SDIDTK terdiri dari 10 pertanyaan tervalidasi.",
    pertanyaan: [
      {
        no: 1,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat berjalan sendiri di dalam ruangan tanpa berpegangan dan tanpa sering jatuh?",
        petunjuk: "Anak mampu berjalan mandiri minimal 5-10 langkah.",
      },
      {
        no: 2,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat berjalan mundur 2 sampai 3 langkah?",
        petunjuk: "Amati saat anak berjalan/menarik mainan mundur.",
      },
      {
        no: 3,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat merangkak naik tangga atau menaiki tangga dengan bantuan?",
        petunjuk: "Amati kemampuan menaiki anak tangga secara aman.",
      },
      {
        no: 4,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menumpuk 3 kubus/balok kayu di atas satu sama lain?",
        petunjuk: "Tunjukkan cara membuat menara dari 3 balok kayu.",
      },
      {
        no: 5,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat membuat coretan di atas kertas dengan pensil/krayon?",
        petunjuk: "Berikan krayon dan kertas di atas meja/lantai.",
      },
      {
        no: 6,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat mengeluarkan benda kecil dari botol bening dengan cara membalikkan botol?",
        petunjuk: "Masukkan benda kecil ke dalam botol bening di depan anak.",
      },
      {
        no: 7,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat mengucapkan sedikitnya 3 sampai 6 kata bermakna selain 'mama' atau 'papa'?",
        petunjuk: "Kata bermakna jelas selain kata mama/papa.",
      },
      {
        no: 8,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat menunjuk dengan jari telunjuk jika ingin sesuatu atau menunjuk gambar yang dinamai?",
        petunjuk: "Amati gestur menunjuk dengan jari telunjuk.",
      },
      {
        no: 9,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat menunjukkan mainannya kepada Anda untuk memperlihatkan kegembiraan?",
        petunjuk: "Interaksi berbagi perhatian (joint attention) dengan orang tua.",
      },
      {
        no: 10,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat melepas pakaian sederhana seperti kaus kaki atau topi sendiri?",
        petunjuk: "Amati usaha anak saat mencoba melepas kaus kaki atau topi.",
      },
    ],
  },
  18: {
    usiaBulan: 18,
    namaGroup: "KPSP Usia 18 Bulan",
    deskripsi: "Untuk anak usia 18 bulan (rentang 18 - <24 bulan). Kuesioner resmi Kemenkes RI SDIDTK terdiri dari 10 pertanyaan tervalidasi.",
    pertanyaan: [
      {
        no: 1,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat berjalan dengan lancar tanpa jatuh?",
        petunjuk: "Keseimbangan dan koordinasi berjalan anak sudah mantap.",
      },
      {
        no: 2,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat menendang bola ke depan tanpa berpegangan?",
        petunjuk: "Letakkan bola di depan anak dan minta menendangnya.",
      },
      {
        no: 3,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat naik tangga dengan memegang tangan Anda atau pegangan tangga?",
        petunjuk: "Anak melangkah naik satu per satu anak tangga.",
      },
      {
        no: 4,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menumpuk 4 kubus/balok kayu di atas satu sama lain?",
        petunjuk: "Berikan 4 kubus dan ajak menumpuknya menjadi menara.",
      },
      {
        no: 5,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat membalik halaman buku (meski 2-3 halaman sekaligus)?",
        petunjuk: "Berikan buku cerita bergambar dengan lembaran tebal.",
      },
      {
        no: 6,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat memasukkan benda kecil ke dalam botol bening?",
        petunjuk: "Amati koordinasi mata dan tangan saat memasukkan benda ke lubang botol.",
      },
      {
        no: 7,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat mengucapkan sedikitnya 6 kata bermakna?",
        petunjuk: "Kosakata aktif yang diucapkan secara bermakna.",
      },
      {
        no: 8,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat menunjuk minimal 1 bagian tubuhnya (misal: mata, hidung, kaki) saat diminta?",
        petunjuk: "Tanyakan 'Mana mata adik?' tanpa menunjuk duluan.",
      },
      {
        no: 9,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat menirukan pekerjaan rumah tangga sederhana (misal: menyapu, mengelap meja)?",
        petunjuk: "Anak meniru aktivitas harian orang tua secara spontan.",
      },
      {
        no: 10,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat makan sendiri menggunakan sendok meski sedikit tumpah?",
        petunjuk: "Amati usaha makan mandiri menggunakan sendok.",
      },
    ],
  },
  21: {
    usiaBulan: 21,
    namaGroup: "KPSP Usia 21 Bulan",
    deskripsi: "Untuk anak usia 21 bulan (rentang 21 - <24 bulan). Kuesioner resmi Kemenkes RI SDIDTK terdiri dari 10 pertanyaan tervalidasi.",
    pertanyaan: [
      {
        no: 1,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat berlari pelan tanpa sering terjatuh?",
        petunjuk: "Amati gerakan lari anak di tempat lapang yang aman.",
      },
      {
        no: 2,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat naik tangga sendiri sambil memegang dinding atau pegangan tangga?",
        petunjuk: "Anak naik tangga satu per satu melangkah dengan aman.",
      },
      {
        no: 3,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat melempar bola kecil ke depan dengan ayunan tangan?",
        petunjuk: "Berikan bola kecil dan minta anak melemparnya ke depan.",
      },
      {
        no: 4,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menumpuk 5 kubus/balok kayu kecil di atas satu sama lain?",
        petunjuk: "Demonstrasikan menara dari 5 kubus kayu kecil.",
      },
      {
        no: 5,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat membalik halaman buku satu per satu?",
        petunjuk: "Berikan buku cerita bergambar dan amati kelincahan jarinya.",
      },
      {
        no: 6,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat memindahkan benda/air dari satu wadah ke wadah lain?",
        petunjuk: "Amati saat anak bermain memindahkan benda/air antar wadah.",
      },
      {
        no: 7,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat menggabungkan 2 kata bermakna menjadi kalimat sederhana (misal: 'minta minum', 'mau makan')?",
        petunjuk: "Dua kata terpisah yang diucapkan berurutan membentuk arti.",
      },
      {
        no: 8,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat menunjuk sedikitnya 3 bagian tubuhnya saat Anda sebutkan namanya?",
        petunjuk: "Tanyakan posisi mata, telinga, atau kaki tanpa menunjuk duluan.",
      },
      {
        no: 9,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat makan sendiri menggunakan sendok tanpa banyak tumpah?",
        petunjuk: "Makan mandiri dengan kontrol gerakan tangan yang makin rapi.",
      },
      {
        no: 10,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat memberitahu jika ingin buang air (ompol/pup)?",
        petunjuk: "Menggunakan isyarat kata atau menunjuk celana saat merasa tidak nyaman.",
      },
    ],
  },
  24: {
    usiaBulan: 24,
    namaGroup: "KPSP Usia 24 Bulan",
    deskripsi: "Untuk anak usia 24 bulan (rentang 24 - <30 bulan). Kuesioner resmi Kemenkes RI SDIDTK terdiri dari 10 pertanyaan tervalidasi.",
    pertanyaan: [
      {
        no: 1,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat melompat dengan kedua kaki terangkat bersamaan dari lantai?",
        petunjuk: "Minta anak melompat di tempat di atas lantai rata.",
      },
      {
        no: 2,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat menendang bola besar ke depan tanpa kehilangan keseimbangan?",
        petunjuk: "Letakkan bola di depan anak dan minta menendang kuat.",
      },
      {
        no: 3,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat berjalan turun tangga dengan menapakkan kedua kaki di tiap anak tangga?",
        petunjuk: "Boleh memegang pegangan tangga atau dinding saat turun.",
      },
      {
        no: 4,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menumpuk 6 kubus/balok kayu kecil di atas satu sama lain?",
        petunjuk: "Beri 6 kubus kayu dan ajak membuat menara tinggi.",
      },
      {
        no: 5,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menirukan garis tegak (vertikal) di atas kertas setelah Anda mencontohkannya?",
        petunjuk: "Buat garis lurus tegak di kertas dan minta anak menirunya.",
      },
      {
        no: 6,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat memutar atau membuka tutup wadah/botol sederhana?",
        petunjuk: "Amati eksplorasi tangan anak terhadap botol/toples kecil.",
      },
      {
        no: 7,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat mengucapkan minimal 10 kata yang memiliki arti jelas?",
        petunjuk: "Kosakata aktif anak yang dipahami oleh anggota keluarga.",
      },
      {
        no: 8,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat menunjuk gambar yang dinamai (misal: kucing, kuda, mobil)?",
        petunjuk: "Tunjukkan buku bergambar dan minta anak menunjuk gambar spesifik.",
      },
      {
        no: 9,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat mengenakan pakaian sederhana sendiri (celana pendek karet)?",
        petunjuk: "Amati usaha memakai celana atau pakaian longgar sendiri.",
      },
      {
        no: 10,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak suka menirukan kegiatan rumah tangga sederhana (seperti menyapu, mengelap)?",
        petunjuk: "Anak meniru aktivitas harian orang tua secara spontan.",
      },
    ],
  },
  30: {
    usiaBulan: 30,
    namaGroup: "KPSP Usia 30 Bulan",
    deskripsi: "Untuk anak usia 30 bulan (rentang 30 - <36 bulan). Kuesioner resmi Kemenkes RI SDIDTK terdiri dari 10 pertanyaan tervalidasi.",
    pertanyaan: [
      {
        no: 1,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat melompat jauh ke depan dengan kedua kaki bersamaan?",
        petunjuk: "Minta anak melompat ke depan melintasi jarak pendek.",
      },
      {
        no: 2,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat berdiri di atas satu kaki selama 1-2 detik tanpa berpegangan?",
        petunjuk: "Minta anak mengangkat satu kaki sejenak.",
      },
      {
        no: 3,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat mengayuh sepeda roda tiga sejauh beberapa meter?",
        petunjuk: "Amati kayuhan pedal sepeda roda tiga di permukaan datar.",
      },
      {
        no: 4,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menumpuk 8 kubus/balok kayu di atas satu sama lain?",
        petunjuk: "Susun 8 balok kayu menjadi menara yang stabil.",
      },
      {
        no: 5,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menirukan bentuk garis mendatar (horizontal) atau garis silang (+)?",
        petunjuk: "Contohkan di kertas dan minta anak menirunya.",
      },
      {
        no: 6,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat merangkai manik-manik besar pada tali?",
        petunjuk: "Berikan manik berlubang besar dan tali untuk dirangkai.",
      },
      {
        no: 7,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat menyebutkan nama lengkapnya jika ditanya?",
        petunjuk: "Tanyakan 'Siapa nama lengkap adik?'",
      },
      {
        no: 8,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat menggunakan kalimat 3 kata atau lebih (misal: 'saya mau minum')?",
        petunjuk: "Kalimat lengkap berisi subjek, predikat, dan objek.",
      },
      {
        no: 9,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat mencuci tangan sendiri dengan sabun dan mengeringkannya?",
        petunjuk: "Amati proses cuci tangan di wastafel.",
      },
      {
        no: 10,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat memakai sepatu sendiri (tanpa tali)?",
        petunjuk: "Memakai sepatu perekat/slip-on secara mandiri.",
      },
    ],
  },
  36: {
    usiaBulan: 36,
    namaGroup: "KPSP Usia 36 Bulan",
    deskripsi: "Untuk anak usia 36 bulan (rentang 36 - <42 bulan). Kuesioner resmi Kemenkes RI SDIDTK terdiri dari 10 pertanyaan tervalidasi.",
    pertanyaan: [
      {
        no: 1,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat melompati kertas seluas 20 cm dengan kedua kaki terangkat bersamaan?",
        petunjuk: "Letakkan lembaran kertas selebar 20 cm di lantai dan minta anak melompatinya.",
      },
      {
        no: 2,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat berdiri di atas satu kaki tanpa berpegangan selama sekurang-kurangnya 3 detik?",
        petunjuk: "Uji keseimbangan berdiri satu kaki tanpa menyenggol perabot.",
      },
      {
        no: 3,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat mengayuh sepeda roda tiga ke depan sejauh 3 meter?",
        petunjuk: "Mengayuh pedal secara mandiri tanpa didorong.",
      },
      {
        no: 4,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menirukan bentuk lingkaran (O) yang Anda contohkan pada kertas?",
        petunjuk: "Gambarlah lingkaran di kertas dan minta anak menirunya tanpa menjiplak.",
      },
      {
        no: 5,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menumpuk 8 sampai 9 kubus/balok kayu?",
        petunjuk: "Beri kubus kayu dan ajak membuat menara tinggi.",
      },
      {
        no: 6,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menggunting kertas menjadi dua bagian?",
        petunjuk: "Berikan gunting tumpul anak dan lembar kertas.",
      },
      {
        no: 7,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah orang luar (selain keluarga) mengerti sebagian besar kalimat yang diucapkan anak?",
        petunjuk: "Kejelasan artikulasi dan tata bahasa saat bicara.",
      },
      {
        no: 8,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat menyebutkan nama teman bermainnya?",
        petunjuk: "Menyebutkan nama asli/panggilan teman dekatnya.",
      },
      {
        no: 9,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat mengenakan kaus/kemeja sendiri?",
        petunjuk: "Memakai pakaian sendiri tanpa bantuan memegang lubang lengan.",
      },
      {
        no: 10,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat bermain bersama teman secara kooperatif (bergantian)?",
        petunjuk: "Bermain berbagi mainan dan bergantian peran.",
      },
    ],
  },
  42: {
    usiaBulan: 42,
    namaGroup: "KPSP Usia 42 Bulan",
    deskripsi: "Untuk anak usia 42 bulan (rentang 42 - <48 bulan). Kuesioner resmi Kemenkes RI SDIDTK terdiri dari 10 pertanyaan tervalidasi.",
    pertanyaan: [
      {
        no: 1,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat melompat dengan satu kaki (engklek) 2 sampai 3 kali?",
        petunjuk: "Melompat dengan satu kaki di tempat atau ke depan.",
      },
      {
        no: 2,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat berdiri di atas satu kaki selama 4 detik?",
        petunjuk: "Berdiri satu kaki tanpa bantuan atau berpegangan.",
      },
      {
        no: 3,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat menangkap bola besar yang dilemparkan dari jarak 1,5 meter?",
        petunjuk: "Lemparkan bola plastik sedang dari jarak 1,5 meter ke arah tangan anak.",
      },
      {
        no: 4,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menggambar garis silang (+) menirukan contoh Anda?",
        petunjuk: "Buat garis silang tegak lurus di kertas dan minta anak menirunya.",
      },
      {
        no: 5,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menggambar orang dengan minimal 2 bagian tubuh (misal: kepala dan kaki)?",
        petunjuk: "Gambar orang sederhana dengan kepala dan kaki/lengan.",
      },
      {
        no: 6,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menuang air dari teko kecil ke gelas tanpa banyak tumpah?",
        petunjuk: "Amati kontrol motorik halus saat menuang cairan.",
      },
      {
        no: 7,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat menjawab dengan benar jika ditanya 'apa yang kamu lakukan kalau lapar / haus / lelah?'?",
        petunjuk: "Menjawab solusi logis (misal: 'makan', 'minum', 'tidur').",
      },
      {
        no: 8,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak mengerti konsep kata depan (di atas, di bawah, di dalam)?",
        petunjuk: "Minta anak meletakkan mainan 'di atas meja' atau 'di bawah kursi'.",
      },
      {
        no: 9,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat kencing/buang air besar sendiri di toilet tanpa mengompol?",
        petunjuk: "Kemandirian toilet training tanpa harus diingatkan.",
      },
      {
        no: 10,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat mengancingkan baju sendiri?",
        petunjuk: "Memasukkan kancing baju ke lubangnya sendiri.",
      },
    ],
  },
  48: {
    usiaBulan: 48,
    namaGroup: "KPSP Usia 48 Bulan",
    deskripsi: "Untuk anak usia 48 bulan (rentang 48 - <54 bulan). Kuesioner resmi Kemenkes RI SDIDTK terdiri dari 10 pertanyaan tervalidasi.",
    pertanyaan: [
      {
        no: 1,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat berdiri di atas satu kaki selama sekurang-kurangnya 5 detik tanpa berpegangan?",
        petunjuk: "Uji keseimbangan berdiri satu kaki dengan stabil.",
      },
      {
        no: 2,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat melompat dengan satu kaki (engklek) beberapa kali berturut-turut?",
        petunjuk: "Lompatan engklek beruntun dengan seimbang.",
      },
      {
        no: 3,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat melempar bola kecil ke atas atau ke depan dari atas bahu secara terarah?",
        petunjuk: "Ayunkan tangan dari atas bahu untuk melempar bola.",
      },
      {
        no: 4,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menirukan gambar bentuk tanda tambah (+) dan bentuk persegi/segi empat (□)?",
        petunjuk: "Gambarlah persegi di kertas dan minta anak menirunya.",
      },
      {
        no: 5,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menggambar orang dengan sedikitnya 3 bagian tubuh?",
        petunjuk: "Gambar orang terdiri dari minimal kepala, badan, dan tangan/kaki.",
      },
      {
        no: 6,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menggunting mengikuti garis lurus pada kertas?",
        petunjuk: "Menggunakan gunting tumpul menyusuri garis lurus.",
      },
      {
        no: 7,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat menyebutkan minimal 4 warna dasar (merah, kuning, hijau, biru) dengan benar?",
        petunjuk: "Tunjukkan benda/kertas berwarna dan minta anak menyebutkan namanya.",
      },
      {
        no: 8,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat menceritakan kejadian/pengalaman singkat yang baru saja dialaminya?",
        petunjuk: "Menceritakan alur cerita sederhana yang dialami.",
      },
      {
        no: 9,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat memakai baju sendiri tanpa bantuan?",
        petunjuk: "Memakai kemeja/kaus dan celana sendiri.",
      },
      {
        no: 10,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat mencuci tangan dan mengeringkannya sendiri setelah dari toilet?",
        petunjuk: "Prosedur kebersihan diri mandiri setelah dari toilet.",
      },
    ],
  },
  54: {
    usiaBulan: 54,
    namaGroup: "KPSP Usia 54 Bulan",
    deskripsi: "Untuk anak usia 54 bulan (rentang 54 - <60 bulan). Kuesioner resmi Kemenkes RI SDIDTK terdiri dari 10 pertanyaan tervalidasi.",
    pertanyaan: [
      {
        no: 1,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat berdiri di atas satu kaki selama 6 detik tanpa berpegangan?",
        petunjuk: "Uji keseimbangan berdiri satu kaki selama 6 detik penuh.",
      },
      {
        no: 2,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat berjalan jinjit (dengan tumit terangkat) sejauh 4 langkah?",
        petunjuk: "Berjalan jinjit seimbang tanpa menapakkan tumit.",
      },
      {
        no: 3,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat menangkap bola kecil yang dilemparkan kepadanya dari jarak 1,5 meter?",
        petunjuk: "Menangkap bola tenis/kecil dengan kedua tangan.",
      },
      {
        no: 4,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menggambar bentuk segi empat (□) menirukan contoh tanpa bantuan?",
        petunjuk: "Sisi-sisi segi empat terbentuk jelas dan tertutup.",
      },
      {
        no: 5,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menggambar orang dengan minimal 4 bagian tubuh?",
        petunjuk: "Memiliki kepala, badan, 2 lengan, atau 2 kaki.",
      },
      {
        no: 6,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat memilih mana garis yang lebih panjang dari 2 garis yang ditunjukkan?",
        petunjuk: "Buat 2 garis berbeda panjang di kertas dan minta tunjukkan yang lebih panjang.",
      },
      {
        no: 7,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat menjawab fungsi benda (misal: 'kursi untuk apa?', 'pensil untuk apa?')?",
        petunjuk: "Menjelaskan guna benda umum dengan benar.",
      },
      {
        no: 8,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat menyebutkan lawan kata (misal: 'gajah besar, tikus...', 'es dingin, api...')?",
        petunjuk: "Menjawab kata oposisi dengan tepat.",
      },
      {
        no: 9,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat memakai celana dan baju sendiri termasuk memasang kancing?",
        petunjuk: "Kemandirian berbusana lengkap.",
      },
      {
        no: 10,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat bermain permainan beraturan (seperti ular tangga, petak umpet) bersama teman?",
        petunjuk: "Mengerti dan mengikuti aturan permainan kelompok.",
      },
    ],
  },
  60: {
    usiaBulan: 60,
    namaGroup: "KPSP Usia 60 Bulan",
    deskripsi: "Untuk anak usia 60 bulan (rentang 60 - <66 bulan). Kuesioner resmi Kemenkes RI SDIDTK terdiri dari 10 pertanyaan tervalidasi.",
    pertanyaan: [
      {
        no: 1,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat berdiri di atas satu kaki selama 6 detik atau lebih?",
        petunjuk: "Keseimbangan tubuh berdiri satu kaki stabil.",
      },
      {
        no: 2,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat berjalan tumit ke ujung jari (heel-to-toe walk) sepanjang garis lurus sejauh 4 langkah?",
        petunjuk: "Berjalan menyusuri garis lurus dengan tumit menyentuh jemari kaki depan.",
      },
      {
        no: 3,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat melompat dengan satu kaki (engklek) sejauh 5 kali lompatan?",
        petunjuk: "Lompatan engklek lancar 5 kali.",
      },
      {
        no: 4,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menggambar bentuk segitiga (△) menirukan contoh?",
        petunjuk: "Gambarlah segitiga di kertas dan minta anak menirunya.",
      },
      {
        no: 5,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menggambar orang dengan sedikitnya 6 bagian tubuh (kepala, badan, 2 lengan, 2 kaki)?",
        petunjuk: "Gambar orang proporsional dengan minimal 6 bagian organ.",
      },
      {
        no: 6,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menuliskan huruf atau angka sederhana?",
        petunjuk: "Menulis huruf/angka yang bisa dibaca.",
      },
      {
        no: 7,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak mengerti arti 4 kata depan (di atas, di bawah, di depan, di belakang)?",
        petunjuk: "Mengikuti instruksi posisi posisi benda.",
      },
      {
        no: 8,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat menyebutkan nama-nama hari dalam seminggu secara berurutan?",
        petunjuk: "Menyebutkan Senin sampai Minggu secara urut.",
      },
      {
        no: 9,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat mengikat tali sepatu atau memasang kancing kemeja sendiri?",
        petunjuk: "Keterampilan motorik halus dan kemandirian berpakaian.",
      },
      {
        no: 10,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat menyiapkan makanan sederhana (misal: mengoles mentega pada roti)?",
        petunjuk: "Mengoles selai/mentega pada roti sendiri.",
      },
    ],
  },
  66: {
    usiaBulan: 66,
    namaGroup: "KPSP Usia 66 Bulan",
    deskripsi: "Untuk anak usia 66 bulan (rentang 66 - <72 bulan). Kuesioner resmi Kemenkes RI SDIDTK terdiri dari 10 pertanyaan tervalidasi.",
    pertanyaan: [
      {
        no: 1,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat berdiri di atas satu kaki selama 8 hingga 10 detik tanpa berpegangan?",
        petunjuk: "Uji keseimbangan statis satu kaki 8-10 detik.",
      },
      {
        no: 2,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat berjalan mundur dengan tumit menempel ke ujung jari sepanjang garis lurus?",
        petunjuk: "Jalan mundur tandem sejauh beberapa langkah.",
      },
      {
        no: 3,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat menangkap bola tenis/bola kecil dengan satu tangan?",
        petunjuk: "Lemparkan bola kecil dan amati kemampuan menangkap satu tangan.",
      },
      {
        no: 4,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menggambar bentuk segitiga dan segi empat dengan sudut-sudut yang jelas?",
        petunjuk: "Sudut-sudut bangun datar tergambar dengan presisi.",
      },
      {
        no: 5,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menggambar orang lengkap dengan sedikitnya 6 bagian tubuh yang proporsional?",
        petunjuk: "Proporsi bagian tubuh tergambar lengkap.",
      },
      {
        no: 6,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menirukan tulisan kata sederhana (misal: 'B-U-K-U')?",
        petunjuk: "Menuliskan kata sederhana menirukan contoh.",
      },
      {
        no: 7,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat menghitung 10 atau lebih benda secara berurutan dengan benar?",
        petunjuk: "Menghitung jumlah kubus/benda 1 sampai 10 satu per satu.",
      },
      {
        no: 8,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak mengerti lawan kata sederhana dan perbandingan (lebih besar/kecil, lebih berat/ringan)?",
        petunjuk: "Menilai konsep perbandingan fisik benda.",
      },
      {
        no: 9,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat mandi sendiri tanpa dibantu?",
        petunjuk: "Kemandirian mandi dan mengeringkan badan.",
      },
      {
        no: 10,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat berpakaian lengkap sendiri dari awal sampai selesai?",
        petunjuk: "Berbusana mandiri tanpa bantuan sama sekali.",
      },
    ],
  },
  72: {
    usiaBulan: 72,
    namaGroup: "KPSP Usia 72 Bulan",
    deskripsi: "Untuk anak usia 72 bulan (usia 6 tahun). Kuesioner resmi Kemenkes RI SDIDTK terdiri dari 10 pertanyaan tervalidasi.",
    pertanyaan: [
      {
        no: 1,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat berdiri di atas satu kaki selama 10 detik atau lebih tanpa bergoyang hebat?",
        petunjuk: "Berdiri satu kaki sangat stabil selama 10 detik.",
      },
      {
        no: 2,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat berjalan jinjit dan berjalan dengan tumit secara bergantian dengan seimbang?",
        petunjuk: "Koordinasi jalan jinjit dan jalan tumit.",
      },
      {
        no: 3,
        sektor: "kasar",
        sektorLabel: "Motorik Kasar",
        teks: "Apakah anak dapat melompati rintangan setinggi 20 cm dengan mulus?",
        petunjuk: "Melompati rintangan dengan kedua kaki mendarat seimbang.",
      },
      {
        no: 4,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menggaris/menggambar bentuk belah ketupat (◇) menirukan contoh?",
        petunjuk: "Gambarlah belah ketupat dan minta anak menirunya.",
      },
      {
        no: 5,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menggambar orang secara rinci (memiliki pakaian, jari tangan, mata, hidung, mulut)?",
        petunjuk: "Detail gambar orang sangat kaya dan rinci.",
      },
      {
        no: 6,
        sektor: "halus",
        sektorLabel: "Motorik Halus",
        teks: "Apakah anak dapat menulis nama depannya sendiri dengan huruf kapital/kecil yang jelas?",
        petunjuk: "Kemampuan menuliskan nama depan secara mandiri.",
      },
      {
        no: 7,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat menyebutkan fungsi dari 5 benda yang umum digunakan sehari-hari?",
        petunjuk: "Menjelaskan fungsi 5 benda harian.",
      },
      {
        no: 8,
        sektor: "bicara",
        sektorLabel: "Bicara & Bahasa",
        teks: "Apakah anak dapat menyebutkan bahan pembuat benda (misal: 'sendok terbuat dari apa?', 'pintu terbuat dari apa?')?",
        petunjuk: "Menjelaskan material pembuat benda (logam/kayu/kertas).",
      },
      {
        no: 9,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat berpakaian sendiri sepenuhnya, termasuk mengikat tali sepatu atau sabuk?",
        petunjuk: "Berbusana mandiri tingkat lanjut.",
      },
      {
        no: 10,
        sektor: "sosialisasi",
        sektorLabel: "Sosialisasi & Kemandirian",
        teks: "Apakah anak dapat mengikuti aturan permainan kelompok yang rumit tanpa curang?",
        petunjuk: "Kepatuhan pada aturan dan kematangan sosial.",
      },
    ],
  },
};

export function hitungKpsp(jawaban: Record<number, KpspJawaban>): KpspHasil {
  let totalYa = 0;
  let totalTidak = 0;

  Object.values(jawaban).forEach((v) => {
    if (v === "ya") totalYa++;
    if (v === "tidak") totalTidak++;
  });

  if (totalYa >= 9) {
    return {
      totalYa,
      totalTidak,
      kategori: "sesuai",
      label: "Perkembangan Sesuai Umur (S)",
      saran: "Perkembangan anak sesuai dengan usianya (9–10 'YA'). Beri pujian pada ibu/pengasuh. Teruskan pola asuh dan berikan stimulasi tumbuh kembang sesuai kelompok umur. Lakukan jadwal skrining KPSP berikutnya saat usia 6 bulan.",
    };
  }

  if (totalYa >= 7) {
    return {
      totalYa,
      totalTidak,
      kategori: "meragukan",
      label: "Perkembangan Meragukan (M)",
      saran: "Perkembangan anak tergolong meragukan (7–8 'YA'). Anjurkan ibu/pengasuh untuk memberikan stimulasi lebih sering dan intensif, terutama pada sektor yang belum dijawab 'YA'. Lakukan evaluasi & skrining ulang KPSP dalam 2 minggu ke depan.",
    };
  }

  return {
    totalYa,
    totalTidak,
    kategori: "penyimpangan",
    label: "Kemungkinan Penyimpangan Perkembangan (P)",
    saran: "Kemungkinan terdapat penyimpangan perkembangan (<= 6 'YA'). Segera rujuk anak ke Fasilitas Kesehatan Rujukan (Klinik Tumbuh Kembang / Dokter Spesialis Anak) for evaluasi diagnostik serta penanganan intervensi dini komprehensif.",
  };
}

export function sektorTerabaikan(
  pertanyaanList: KpspQuestion[],
  jawaban: Record<number, KpspJawaban>
): KpspQuestion[] {
  return pertanyaanList.filter((q) => jawaban[q.no] === "tidak");
}
